### ISSUE TITLE
Time zone names resource bundle not found

### ISSUE THREAD

**Issue by galderz** [graalvm/mandrel#106]
I don't think this is a Mandrel issue per se yet, but I thought it's interesting enough to track it here and see if we can improve this.

The test case is [here](https://github.com/galderz/mendrugo/tree/master/timezones). If I run that example with Mandrel 20.1.0 Final release on centos 7 it works fine. However, if I build 20.1 branch with the same commit as the Final tag, it fails with:

```
❯ make
rm -drf reports
rm -f timezones
rm -f *.class
javac Timezones.java
native-image Timezones
[timezones:28456]    classlist:   2,589.57 ms,  0.96 GB
[timezones:28456]        (cap):   1,234.49 ms,  0.96 GB
[timezones:28456]        setup:   4,128.09 ms,  0.96 GB
[timezones:28456]     (clinit):     319.95 ms,  1.70 GB
[timezones:28456]   (typeflow):   6,128.10 ms,  1.70 GB
[timezones:28456]    (objects):   7,609.39 ms,  1.70 GB
[timezones:28456]   (features):     481.57 ms,  1.70 GB
[timezones:28456]     analysis:  14,927.75 ms,  1.70 GB
[timezones:28456]     universe:     544.48 ms,  1.70 GB
[timezones:28456]      (parse):   1,754.77 ms,  1.70 GB
[timezones:28456]     (inline):   2,108.05 ms,  1.70 GB
[timezones:28456]    (compile):  10,259.08 ms,  2.32 GB
[timezones:28456]      compile:  15,081.29 ms,  2.32 GB
[timezones:28456]        image:   2,518.98 ms,  2.32 GB
[timezones:28456]        write:     289.85 ms,  2.32 GB
[timezones:28456]      [total]:  40,565.11 ms,  2.32 GB
./timezones
Exception in thread "main" java.util.MissingResourceException: Resource bundle not found sun.util.resources.TimeZoneNames. Register the resource bundle using the option -H:IncludeResourceBundles=sun.util.resources.TimeZoneNames.
	at com.oracle.svm.core.jdk.LocalizationSupport.getCached(LocalizationSupport.java:66)
	at sun.util.resources.Bundles.loadBundleOf(Bundles.java:52)
	at sun.util.resources.Bundles.of(Bundles.java:106)
	at sun.util.resources.LocaleData$1.run(LocaleData.java:185)
	at sun.util.resources.LocaleData$1.run(LocaleData.java:182)
	at java.security.AccessController.doPrivileged(AccessController.java:83)
	at sun.util.resources.LocaleData.getBundle(LocaleData.java:182)
	at sun.util.resources.LocaleData.getTimeZoneNames(LocaleData.java:114)
	at sun.util.locale.provider.LocaleResources.getTimeZoneNames(LocaleResources.java:270)
	at sun.util.cldr.CLDRTimeZoneNameProviderImpl.deriveFallbackName(CLDRTimeZoneNameProviderImpl.java:170)
	at sun.util.cldr.CLDRTimeZoneNameProviderImpl.getDisplayNameArray(CLDRTimeZoneNameProviderImpl.java:93)
	at sun.util.locale.provider.TimeZoneNameProviderImpl.getDisplayName(TimeZoneNameProviderImpl.java:99)
	at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getName(TimeZoneNameUtility.java:271)
	at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getObject(TimeZoneNameUtility.java:229)
	at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getObject(TimeZoneNameUtility.java:215)
	at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObjectImpl(LocaleSubstitutions.java:150)
	at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObject(LocaleSubstitutions.java:242)
	at sun.util.locale.provider.TimeZoneNameUtility.retrieveDisplayNamesImpl(TimeZoneNameUtility.java:197)
	at sun.util.locale.provider.TimeZoneNameUtility.retrieveDisplayName(TimeZoneNameUtility.java:150)
	at java.util.TimeZone.getDisplayName(TimeZone.java:401)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:4049)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:4151)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:3956)
	at java.util.Formatter$FormatSpecifier.printDateTime(Formatter.java:2984)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2885)
	at java.util.Formatter.format(Formatter.java:2673)
	at java.util.Formatter.format(Formatter.java:2609)
	at java.lang.String.format(String.java:2897)
	at Timezones.main(Timezones.java:8)
make: *** [run] Error 1
```

The Mandrel code is the same. I'm building with mandrel-packaging (master) which should work the same way either way. The jdk is slightly different. I'm using jdk11u-dev of today (12th August) while the Final release is using 11.0.8.

I'll carry on exploring.

**Comment by Karm** [comment]
@galderz I guess I could incorporate that Timezone test in  https://github.com/Karm/graal/tree/test-for-issue-2265/integration-tests  alongside randomNumbers in https://github.com/Karm/graal/tree/test-for-issue-2265/integration-tests/apps

**Comment by galderz** [comment]
@Karm Yeah, I think that's a good idea. I'm trying to narrow it down further today. I'm first testing with locally build mandrel with 11.0.8 (as opposed to jdk11u-dev) and see what happens.

**Comment by galderz** [comment]
Just built [11.0.8+10 tag](https://github.com/openjdk/jdk11u/tree/jdk-11.0.8%2B10) locally, and mandrel on top of that. It works fine.

So, this would appear to indicate that something coming up in 11.0.9 is causing the issue...

**Comment by galderz** [comment]
Or, it could be a random issue...

**Comment by galderz** [comment]
I don't think this is a random issue at this point. It seems pretty consistent: when I expect it to fail it fails, when it doesn't it doesn't.

I could be completely wrong, but this issue might be somehow related to the changes in https://github.com/openjdk/jdk11u-dev/commit/fb910780651a3fce4940c498d470c01027c1c7c1. It touches the same area shown in the stacktrace.

**Comment by galderz** [comment]
Note, that change is from Feb but was only integrated into JDK 11 post 11.0.8 cut off (see [newer commits](https://github.com/openjdk/jdk11u-dev/commits/master?after=8fb4ba590ec65b95f0e99323317cc91d5c1d312e+34&branch=master) vs [11.0.8 cut off](https://github.com/openjdk/jdk11u/commits/jdk-11.0.8%2B10))

**Comment by jerboaa** [comment]
The referenced change is in 11.0.9+1 and onwards. See:
https://bugs.openjdk.java.net/browse/JDK-8236548

**Comment by jerboaa** [comment]
@galderz I don't think this is a mandrel issue. Code which relies on timezones needs to add the `-H:IncludeResourceBundles=sun.util.resources.TimeZoneNames` switch when generating the native image.

Baseline build is mandrel 20.1.0.2 (latest dev code of mandrel/20.1 branch, with latest 11.0.9+4 EA build):

```
$ ./substratevm/svmbuild/vm/bin/java -version
openjdk version "11.0.9-ea" 2020-10-20
OpenJDK Runtime Environment GraalVM 20.1.0.2-dev (build 11.0.9-ea+4)
OpenJDK 64-Bit Server VM GraalVM 20.1.0.2-dev (build 11.0.9-ea+4, mixed mode, sharing)
```

Without `-H:IncludeResourceBundles=sun.util.resources.TimeZoneNames`:

```
$ ./substratevm/svmbuild/vm/bin/native-image -J-ea -J-esa Timezones tzonez
[tzonez:67463]    classlist:   5,603.34 ms,  1.19 GB
[tzonez:67463]        (cap):     624.81 ms,  1.19 GB
[tzonez:67463]        setup:   2,106.27 ms,  1.19 GB
[tzonez:67463]     (clinit):     167.87 ms,  2.31 GB
[tzonez:67463]   (typeflow):   5,731.49 ms,  2.31 GB
[tzonez:67463]    (objects):   7,727.43 ms,  2.31 GB
[tzonez:67463]   (features):     227.97 ms,  2.31 GB
[tzonez:67463]     analysis:  14,051.41 ms,  2.31 GB
[tzonez:67463]     universe:     389.95 ms,  2.31 GB
[tzonez:67463]      (parse):   2,215.88 ms,  2.31 GB
[tzonez:67463]     (inline):   2,874.81 ms,  2.31 GB
[tzonez:67463]    (compile):  14,543.70 ms,  4.78 GB
[tzonez:67463]      compile:  23,789.35 ms,  4.78 GB
[tzonez:67463]        image:   1,483.60 ms,  4.78 GB
[tzonez:67463]        write:     183.72 ms,  4.78 GB
[tzonez:67463]      [total]:  47,873.92 ms,  4.78 GB
$ ./tzonez 
Exception in thread "main" java.util.MissingResourceException: Resource bundle not found sun.util.resources.TimeZoneNames. Register the resource bundle using the option -H:IncludeResourceBundles=sun.util.resources.TimeZoneNames.
	at com.oracle.svm.core.jdk.LocalizationSupport.getCached(LocalizationSupport.java:66)
	at sun.util.resources.Bundles.loadBundleOf(Bundles.java:52)
	at sun.util.resources.Bundles.of(Bundles.java:106)
	at sun.util.resources.LocaleData$1.run(LocaleData.java:185)
	at sun.util.resources.LocaleData$1.run(LocaleData.java:182)
	at java.security.AccessController.doPrivileged(AccessController.java:83)
	at sun.util.resources.LocaleData.getBundle(LocaleData.java:182)
	at sun.util.resources.LocaleData.getTimeZoneNames(LocaleData.java:114)
	at sun.util.locale.provider.LocaleResources.getTimeZoneNames(LocaleResources.java:270)
	at sun.util.cldr.CLDRTimeZoneNameProviderImpl.deriveFallbackName(CLDRTimeZoneNameProviderImpl.java:170)
	at sun.util.cldr.CLDRTimeZoneNameProviderImpl.getDisplayNameArray(CLDRTimeZoneNameProviderImpl.java:93)
	at sun.util.locale.provider.TimeZoneNameProviderImpl.getDisplayName(TimeZoneNameProviderImpl.java:99)
	at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getName(TimeZoneNameUtility.java:271)
	at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getObject(TimeZoneNameUtility.java:229)
	at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getObject(TimeZoneNameUtility.java:215)
	at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObjectImpl(LocaleSubstitutions.java:150)
	at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObject(LocaleSubstitutions.java:242)
	at sun.util.locale.provider.TimeZoneNameUtility.retrieveDisplayNamesImpl(TimeZoneNameUtility.java:197)
	at sun.util.locale.provider.TimeZoneNameUtility.retrieveDisplayName(TimeZoneNameUtility.java:150)
	at java.util.TimeZone.getDisplayName(TimeZone.java:401)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:4049)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:4151)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:3956)
	at java.util.Formatter$FormatSpecifier.printDateTime(Formatter.java:2984)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2885)
	at java.util.Formatter.format(Formatter.java:2673)
	at java.util.Formatter.format(Formatter.java:2609)
	at java.lang.String.format(String.java:2897)
	at Timezones.main(Timezones.java:8)
```

With `-H:IncludeResourceBundles=sun.util.resources.TimeZoneNames`:

```
$ ./substratevm/svmbuild/vm/bin/native-image -J-ea -J-esa -H:IncludeResourceBundles=sun.util.resources.TimeZoneNames Timezones tzonez
[tzonez:67662]    classlist:   5,617.69 ms,  1.69 GB
[tzonez:67662]        (cap):     713.68 ms,  1.69 GB
[tzonez:67662]        setup:   2,380.23 ms,  1.69 GB
[tzonez:67662]     (clinit):     211.95 ms,  1.69 GB
[tzonez:67662]   (typeflow):   6,336.03 ms,  1.69 GB
[tzonez:67662]    (objects):   8,084.55 ms,  1.69 GB
[tzonez:67662]   (features):     260.95 ms,  1.69 GB
[tzonez:67662]     analysis:  15,108.00 ms,  1.69 GB
[tzonez:67662]     universe:     384.06 ms,  1.69 GB
[tzonez:67662]      (parse):   2,181.34 ms,  2.27 GB
[tzonez:67662]     (inline):   1,779.81 ms,  2.27 GB
[tzonez:67662]    (compile):  14,671.53 ms,  4.71 GB
[tzonez:67662]      compile:  22,209.83 ms,  4.71 GB
[tzonez:67662]        image:   1,318.09 ms,  4.71 GB
[tzonez:67662]        write:     196.07 ms,  4.71 GB
[tzonez:67662]      [total]:  47,485.94 ms,  4.71 GB
$ ./tzonez 
Thu Aug 20 17:12:38 CEST 2020
Central European Standard Time
```

`Timezones.java` is this:

```
$ cat Timezones.java 
import java.util.Date;
import java.util.TimeZone;

public class Timezones
{
    public static void main(String[] args)
    {
        System.out.println(String.format(
            "%tc", new Date()
        ));

        final var tz = TimeZone.getDefault();
        System.out.println(tz.getDisplayName());
    }
}
```

**Comment by galderz** [comment]
Note that GraalVM 20.1 added this warning:

```
-H:IncludeAllTimeZones and -H:IncludeTimeZones are now deprecated. Native-image includes all timezonesby default.
```

So, if native image includes all timezones, it would not make sense to need `-H:IncludeResourceBundles=sun.util.resources.TimeZoneNames`

**Comment by galderz** [comment]
It could be that GraalVM needs to add `-H:IncludeResourceBundles=sun.util.resources.TimeZoneNames` automatically to honor the warning, given the changes in 11.0.9, or the other possibility is that there's a bug triggered by the 11.0.9 change above.

**Comment by galderz** [comment]
`io.quarkus.it.mongodb.panache.reactive.NativeMongodbPanacheResourceIT` is affected by this, see [here](https://gist.github.com/galderz/bc6362c732c6d0c8bdc557a64e24409e#file-gistfile1-txt-L231).

**Comment by galderz** [comment]
`io.quarkus.it.quartz.QuartzITCase` also affected, see [here](https://gist.github.com/galderz/538813773faa1b3b8bca010773a7cf54#file-gistfile1-txt-L125).

**Comment by galderz** [comment]
`io.quarkus.it.spring.InjectedSpringBeansResourceIT.testSessionScope` too, see [here](https://gist.github.com/galderz/5b834d70a3d2d96e59aa0a5635f1216a#file-gistfile1-txt-L165).

**Comment by jerboaa** [comment]
> Note that GraalVM 20.1 added this warning:
> 
> ```
> -H:IncludeAllTimeZones and -H:IncludeTimeZones are now deprecated. Native-image includes all timezonesby default.
> ```
> 
> So, if native image includes all timezones, it would not make sense to need `-H:IncludeResourceBundles=sun.util.resources.TimeZoneNames`

Why? The former is in relation to time zones pre-inititialized in the image, the later is in relation to included l10n. See https://github.com/graalvm/mandrel/blob/mandrel/20.1/substratevm/RESOURCES.md

**Comment by jerboaa** [comment]
This is actually caused by this fix in OpenJDK 11 (in 11.0.9+1 and onwards):
https://bugs.openjdk.java.net/browse/JDK-8236548

**Comment by jerboaa** [comment]
This fix changes caching of the 'en' locale. In 11.0.8 'en' locales were cached and with 11.0.9+1 this is no longer the case. Thus, native-image on 11.0.9+1 (and better) needs the extra resource when it's generating the image. In fact, for any language **not** English a native image generated with 11.0.8 fails the same way as 11.0.9 EA now does also with the English language:

```
$ ./substratevm/svmbuild/vm/bin/java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment GraalVM 20.1.0.2-dev (build 11.0.8+10)
OpenJDK 64-Bit Server VM GraalVM 20.1.0.2-dev (build 11.0.8+10, mixed mode, sharing)
$ ./substratevm/svmbuild/vm/bin/native-image -J-Duser.country=CA -J-Duser.language=fr Timezones tzonez
[tzonez:79276]    classlist:   7 417,73 ms,  1,18 GB
[tzonez:79276]        (cap):     506,07 ms,  1,18 GB
[tzonez:79276]        setup:   1 475,71 ms,  1,18 GB
[tzonez:79276]     (clinit):     151,72 ms,  1,69 GB
[tzonez:79276]   (typeflow):   3 916,16 ms,  1,69 GB
[tzonez:79276]    (objects):   4 706,14 ms,  1,69 GB
[tzonez:79276]   (features):     184,43 ms,  1,69 GB
[tzonez:79276]     analysis:   9 129,22 ms,  1,69 GB
[tzonez:79276]     universe:     246,30 ms,  1,69 GB
[tzonez:79276]      (parse):   1 029,95 ms,  1,69 GB
[tzonez:79276]     (inline):   1 985,22 ms,  2,24 GB
[tzonez:79276]    (compile):   7 286,85 ms,  3,18 GB
[tzonez:79276]      compile:  10 774,64 ms,  3,18 GB
[tzonez:79276]        image:   1 574,50 ms,  3,18 GB
[tzonez:79276]        write:     143,94 ms,  3,18 GB
[tzonez:79276]      [total]:  30 938,46 ms,  3,18 GB
$ ./tzonez 
Exception in thread "main" java.util.MissingResourceException: Resource bundle not found sun.util.resources.TimeZoneNames. Register the resource bundle using the option -H:IncludeResourceBundles=sun.util.resources.TimeZoneNames.
	at com.oracle.svm.core.jdk.LocalizationSupport.getCached(LocalizationSupport.java:66)
	at sun.util.resources.Bundles.loadBundleOf(Bundles.java:52)
	at sun.util.resources.Bundles.of(Bundles.java:106)
	at sun.util.resources.LocaleData$1.run(LocaleData.java:185)
	at sun.util.resources.LocaleData$1.run(LocaleData.java:182)
	at java.security.AccessController.doPrivileged(AccessController.java:83)
	at sun.util.resources.LocaleData.getBundle(LocaleData.java:182)
	at sun.util.resources.LocaleData.getTimeZoneNames(LocaleData.java:114)
	at sun.util.locale.provider.LocaleResources.getTimeZoneNames(LocaleResources.java:271)
	at sun.util.cldr.CLDRTimeZoneNameProviderImpl.deriveFallbackName(CLDRTimeZoneNameProviderImpl.java:164)
	at sun.util.cldr.CLDRTimeZoneNameProviderImpl.getDisplayNameArray(CLDRTimeZoneNameProviderImpl.java:99)
	at sun.util.locale.provider.TimeZoneNameProviderImpl.getDisplayName(TimeZoneNameProviderImpl.java:99)
	at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getName(TimeZoneNameUtility.java:271)
	at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getObject(TimeZoneNameUtility.java:229)
	at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getObject(TimeZoneNameUtility.java:215)
	at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObjectImpl(LocaleSubstitutions.java:150)
	at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObject(LocaleSubstitutions.java:242)
	at sun.util.locale.provider.TimeZoneNameUtility.retrieveDisplayNamesImpl(TimeZoneNameUtility.java:197)
	at sun.util.locale.provider.TimeZoneNameUtility.retrieveDisplayName(TimeZoneNameUtility.java:150)
	at java.util.TimeZone.getDisplayName(TimeZone.java:401)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:4049)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:4151)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:3956)
	at java.util.Formatter$FormatSpecifier.printDateTime(Formatter.java:2984)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2885)
	at java.util.Formatter.format(Formatter.java:2673)
	at java.util.Formatter.format(Formatter.java:2609)
	at java.lang.String.format(String.java:2897)
	at Timezones.main(Timezones.java:8)
```

And with the resource included:

```
$ ./substratevm/svmbuild/vm/bin/native-image -J-Duser.country=CA -J-Duser.language=fr -H:IncludeResourceBundles=sun.util.resources.TimeZoneNames Timezones tzonez
[tzonez:79631]    classlist:   5 956,76 ms,  1,21 GB
[tzonez:79631]        (cap):     661,24 ms,  1,69 GB
[tzonez:79631]        setup:   1 831,82 ms,  1,69 GB
[tzonez:79631]     (clinit):     269,50 ms,  2,71 GB
[tzonez:79631]   (typeflow):   4 311,71 ms,  2,71 GB
[tzonez:79631]    (objects):   5 293,77 ms,  2,71 GB
[tzonez:79631]   (features):     220,60 ms,  2,71 GB
[tzonez:79631]     analysis:  10 301,50 ms,  2,71 GB
[tzonez:79631]     universe:     352,16 ms,  2,71 GB
[tzonez:79631]      (parse):   1 133,11 ms,  2,71 GB
[tzonez:79631]     (inline):   1 048,88 ms,  2,71 GB
[tzonez:79631]    (compile):   7 888,43 ms,  2,71 GB
[tzonez:79631]      compile:  10 676,25 ms,  2,71 GB
[tzonez:79631]        image:   1 417,38 ms,  2,71 GB
[tzonez:79631]        write:     131,75 ms,  2,71 GB
[tzonez:79631]      [total]:  31 033,33 ms,  2,71 GB
$ ./tzonez 
jeu. août 20 19:31:13 CEST 2020
heure normale d’Europe centrale
```

**Comment by jerboaa** [comment]
@galderz My suggestion would be to add `-H:IncludeResourceBundles=sun.util.resources.TimeZoneNames` to quarkus when a native image is being generated so that they can be sure the resource will be there. Previously they were relying on an impl detail of OpenJDK which of course can change (as seen with this bug). Thoughts?

**Comment by Karm** [comment]
@galderz My Jenkins Mandrel 20.2 + Quarkus 1.7.0.Final fails as expected on e.g. [Quartz] (https://gist.github.com/Karm/6806d58c973a2c7d4f3d643fe866ba5a): Is there any Quarkus branch in your repo I can try to build and run the tests with that adds ```-H:IncludeResourceBundles=sun.util.resources.TimeZoneNames```? 
Have you guys tried as
```

<plugin>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-maven-plugin</artifactId>
  <version>${version.quarkus}</version>
  <executions>
    <execution>
      <goals>
        <goal>native-image</goal>
      </goals>
    </execution>
  </executions>
  <configuration>
    <enableHttpUrlHandler>true</enableHttpUrlHandler>
    <additionalBuildArgs>-H:IncludeResourceBundles=sun.util.resources.TimeZoneNames</additionalBuildArgs>
  </configuration>
</plugin>

```
?

**Comment by Karm** [comment]
@zakkak  @jerboaa  Test is added here... https://github.com/Karm/mandrel-integration-tests/pull/1 

Will propose move to https://github.com/graalvm/mandrel-integration-tests soon.
