### ISSUE TITLE
Keycloak native image fails to build with assertions enabled

### ISSUE THREAD

**Issue by galderz** [graalvm/mandrel#111]
```
2020-08-20T14:36:25.2752551Z Fatal error:org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.AssertionError: Clearing of second slot must have cleared the first slot too
2020-08-20T14:36:25.2752762Z 	at parsing org.bouncycastle.math.raw.Nat256.mul(Unknown Source)
2020-08-20T14:36:25.2752953Z 	at method: void org.bouncycastle.math.raw.Nat256.mul(int[], int[], int[])
2020-08-20T14:36:25.2753159Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2580)
2020-08-20T14:36:25.2753388Z 	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:100)
2020-08-20T14:36:25.2753608Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3418)
2020-08-20T14:36:25.2753831Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3220)
2020-08-20T14:36:25.2754050Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1090)
2020-08-20T14:36:25.2754253Z 	at com.oracle.svm.hosted.phases.HostedBytecodeParser.build(HostedGraphBuilderPhase.java:108)
2020-08-20T14:36:25.2754457Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:984)
2020-08-20T14:36:25.2754663Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
2020-08-20T14:36:25.2756050Z 	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:74)
2020-08-20T14:36:25.2756295Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
2020-08-20T14:36:25.2756504Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:214)
2020-08-20T14:36:25.2756704Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
2020-08-20T14:36:25.2756923Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
2020-08-20T14:36:25.2757134Z 	at com.oracle.svm.hosted.code.CompileQueue.defaultParseFunction(CompileQueue.java:726)
2020-08-20T14:36:25.2757340Z 	at com.oracle.svm.hosted.code.CompileQueue.doParse(CompileQueue.java:691)
2020-08-20T14:36:25.2757543Z 	at com.oracle.svm.hosted.code.CompileQueue$ParseTask.run(CompileQueue.java:307)
2020-08-20T14:36:25.2757745Z 	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
2020-08-20T14:36:25.2757961Z 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
2020-08-20T14:36:25.2758165Z 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
2020-08-20T14:36:25.2758368Z 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
2020-08-20T14:36:25.2758719Z 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
2020-08-20T14:36:25.2758926Z 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
2020-08-20T14:36:25.2759131Z 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2020-08-20T14:36:25.2759343Z Caused by: java.lang.AssertionError: Clearing of second slot must have cleared the first slot too
2020-08-20T14:36:25.2759560Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.FrameStateBuilder.clearNonLiveLocals(FrameStateBuilder.java:675)
2020-08-20T14:36:25.2759791Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.createBytecodeExceptionFrameState(BytecodeParser.java:3943)
2020-08-20T14:36:25.2760017Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.emitBytecodeExceptionCheck(BytecodeParser.java:1580)
2020-08-20T14:36:25.2760237Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.maybeEmitExplicitNullCheck(BytecodeParser.java:1535)
2020-08-20T14:36:25.2760528Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genLoadIndexed(BytecodeParser.java:4039)
2020-08-20T14:36:25.2760765Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5202)
2020-08-20T14:36:25.2760982Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3413)
2020-08-20T14:36:25.2761176Z 	... 20 more
```

[Full logs](https://gist.github.com/galderz/3b3637a17332b4e7eee3177ce3d5deae)

**Comment by zakkak** [comment]
This is being tracked upstream https://github.com/oracle/graal/issues/2735

**Comment by galderz** [comment]
Great, thx @zakkak. I'm assigning issue to you.

**Comment by zakkak** [comment]
This is now fixed upstream https://github.com/oracle/graal/commit/929dde28d8ba99b3d044be2b6fb86ce1625a2286
