### ISSUE TITLE
"RSA KeyFactory not available" with Java 11

### ISSUE THREAD

**Issue by galderz** [graalvm/mandrel#12]
Details [here](https://gist.github.com/galderz/da23ed2be4bccbfeffec42c6c6e123ad):

```
[INFO] Running io.quarkus.it.elytron.JCAITCase
...
Caused by: java.security.NoSuchAlgorithmException: RSA KeyFactory not available
	at java.security.KeyFactory.<init>(KeyFactory.java:138)
	at java.security.KeyFactory.getInstance(KeyFactory.java:172)
	at io.quarkus.it.elytron.KeyFactoryEndpoint.verifyRSASig(KeyFactoryEndpoint.java:52)
```

On Quarkus master, happens with Java 11 and GraalVM 19.2. This happened [before](https://github.com/quarkusio/quarkus/issues/1163), but the fix does not seem to work with Java 11.

**Comment by sberyozkin** [comment]
The same issue causes [this failure](https://github.com/quarkusio/quarkus/issues/6588#issuecomment-619906774) with Java 8 update 252:
```
java.security.NoSuchAlgorithmException: RSA KeyFactory not available
	at java.security.KeyFactory.<init>(KeyFactory.java:138)
	at java.security.KeyFactory.getInstance(KeyFactory.java:172)
	at io.smallrye.jwt.KeyUtils.decodePublicKey(KeyUtils.java:211)
	at io.smallrye.jwt.auth.principal.KeyLocationResolver.tryAsPEMPublicKey(KeyLocationResolver.java:277)

```

**Comment by galderz** [comment]
Closing this. The issue has only temporarily appeared when the java version used to compile was ahead of the JDK used by GraalVM to compile to native code. With newer GraalVM versions available, the issue goes away.
