### ISSUE TITLE
Error with jdk11u-dev: undefined reference to JNI_OnLoad_extnet

### ISSUE THREAD

**Issue by galderz** [graalvm/mandrel#13]
Recent changes in oracle/graal master means that we cannot build any native images with jdk11u-dev based JDK.

The error is caused by [this change](https://github.com/graalvm/labs-openjdk-11/commit/9eee9ee40aeb69c6c85d1492a3369c232807f3c0) to Labs JDK and [this change](https://github.com/oracle/graal/commit/8fb8fc502411b3c84308ff5cda4d6c1f775f3920) in oracle/graal. The motivation for this change is unclear. Error below:

```
Linker command ouput:
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
COMPILER_PATH=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/:/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/:/usr/libexec/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/:/usr/lib/gcc/x86_64-redhat-linux/
LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/4.8.5/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-z' 'noexecstack' '-o' '/home/g/workspace/quarkus-with-graal/2020.05.11/quarkus-platform/integration-tests/camel/camel-jsonpath/target/quarkus-universe-integration-tests-camel-jsonpath-999-SNAPSHOT-native-image-source-jar/quarkus-universe-integration-tests-camel-jsonpath-999-SNAPSHOT-runner' '-v' '-L/tmp/SVM-7334457422376522076' '-L/home/g/workspace/quarkus-with-graal/2020.05.11/graalvm/graal/sdk/mxbuild/linux-amd64/GRAALVM_BC62B52CD1_JAVA11/graalvm-bc62b52cd1-java11-20.2.0-dev/lib' '-L/home/g/workspace/quarkus-with-graal/2020.05.11/graalvm/graal/sdk/mxbuild/linux-amd64/GRAALVM_BC62B52CD1_JAVA11/graalvm-bc62b52cd1-java11-20.2.0-dev/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
 /usr/libexec/gcc/x86_64-redhat-linux/4.8.5/collect2 --build-id --no-add-needed --eh-frame-hdr --hash-style=gnu -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o /home/g/workspace/quarkus-with-graal/2020.05.11/quarkus-platform/integration-tests/camel/camel-jsonpath/target/quarkus-universe-integration-tests-camel-jsonpath-999-SNAPSHOT-native-image-source-jar/quarkus-universe-integration-tests-camel-jsonpath-999-SNAPSHOT-runner -z noexecstack /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtbegin.o -L/tmp/SVM-7334457422376522076 -L/home/g/workspace/quarkus-with-graal/2020.05.11/graalvm/graal/sdk/mxbuild/linux-amd64/GRAALVM_BC62B52CD1_JAVA11/graalvm-bc62b52cd1-java11-20.2.0-dev/lib -L/home/g/workspace/quarkus-with-graal/2020.05.11/graalvm/graal/sdk/mxbuild/linux-amd64/GRAALVM_BC62B52CD1_JAVA11/graalvm-bc62b52cd1-java11-20.2.0-dev/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../.. --gc-sections --dynamic-list /tmp/SVM-7334457422376522076/exported_symbols.list --exclude-libs ALL -x /tmp/SVM-7334457422376522076/quarkus-universe-integration-tests-camel-jsonpath-999-SNAPSHOT-runner.o /home/g/workspace/quarkus-with-graal/2020.05.11/graalvm/graal/sdk/mxbuild/linux-amd64/GRAALVM_BC62B52CD1_JAVA11/graalvm-bc62b52cd1-java11-20.2.0-dev/lib/svm/clibraries/linux-amd64/liblibchelper.a /home/g/workspace/quarkus-with-graal/2020.05.11/graalvm/graal/sdk/mxbuild/linux-amd64/GRAALVM_BC62B52CD1_JAVA11/graalvm-bc62b52cd1-java11-20.2.0-dev/lib/libnet.a /home/g/workspace/quarkus-with-graal/2020.05.11/graalvm/graal/sdk/mxbuild/linux-amd64/GRAALVM_BC62B52CD1_JAVA11/graalvm-bc62b52cd1-java11-20.2.0-dev/lib/svm/clibraries/linux-amd64/libstrictmath.a /home/g/workspace/quarkus-with-graal/2020.05.11/graalvm/graal/sdk/mxbuild/linux-amd64/GRAALVM_BC62B52CD1_JAVA11/graalvm-bc62b52cd1-java11-20.2.0-dev/lib/svm/clibraries/linux-amd64/libffi.a /home/g/workspace/quarkus-with-graal/2020.05.11/graalvm/graal/sdk/mxbuild/linux-amd64/GRAALVM_BC62B52CD1_JAVA11/graalvm-bc62b52cd1-java11-20.2.0-dev/lib/libextnet.a /home/g/workspace/quarkus-with-graal/2020.05.11/graalvm/graal/sdk/mxbuild/linux-amd64/GRAALVM_BC62B52CD1_JAVA11/graalvm-bc62b52cd1-java11-20.2.0-dev/lib/libnio.a /home/g/workspace/quarkus-with-graal/2020.05.11/graalvm/graal/sdk/mxbuild/linux-amd64/GRAALVM_BC62B52CD1_JAVA11/graalvm-bc62b52cd1-java11-20.2.0-dev/lib/libjava.a /home/g/workspace/quarkus-with-graal/2020.05.11/graalvm/graal/sdk/mxbuild/linux-amd64/GRAALVM_BC62B52CD1_JAVA11/graalvm-bc62b52cd1-java11-20.2.0-dev/lib/libsunec.a /home/g/workspace/quarkus-with-graal/2020.05.11/graalvm/graal/sdk/mxbuild/linux-amd64/GRAALVM_BC62B52CD1_JAVA11/graalvm-bc62b52cd1-java11-20.2.0-dev/lib/libzip.a /home/g/workspace/quarkus-with-graal/2020.05.11/graalvm/graal/sdk/mxbuild/linux-amd64/GRAALVM_BC62B52CD1_JAVA11/graalvm-bc62b52cd1-java11-20.2.0-dev/lib/svm/clibraries/linux-amd64/libjvm.a -lstdc++ -lpthread -ldl -lz -lrt -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtend.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crtn.o
/tmp/SVM-7334457422376522076/quarkus-universe-integration-tests-camel-jsonpath-999-SNAPSHOT-runner.o:(.data+0x9c0): undefined reference to `JNI_OnLoad_extnet'
collect2: error: ld returned 1 exit status

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:463)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:346)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:505)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:114)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:533)
```

[Longer output](https://gist.github.com/galderz/4268be53e633a586dbb434bc03958cd4)

**Comment by galderz** [comment]
Labs JDK does not present this issue.

**Comment by galderz** [comment]
Asked for explanation for these commits [here](https://github.com/oracle/graal/commit/8fb8fc502411b3c84308ff5cda4d6c1f775f3920).

**Comment by galderz** [comment]
Bob Vandette replied on the core-libs-dev mailing list, see [here](https://mail.openjdk.java.net/pipermail/core-libs-dev/2020-May/066449.html). The JDK15 fix needs to be backported to JDK14 and JDK11 respectively. The relevant JEP is [178](https://openjdk.java.net/jeps/178).

**Comment by galderz** [comment]
[JDK-8244853](https://bugs.openjdk.java.net/browse/JDK-8244853) is the relevant issue. It's in 11.0.8+4.
