### ISSUE TITLE
Mandrel 20.1 branch is broken: missing implementation for runtime call: indexOf1Byte(byte[],int,int,byte)int

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel#137]
```
14:47:06 + javac Hello.java
14:47:07 + native-image Hello
14:47:10 [hello:30957]    classlist:   1,864.97 ms,  0.96 GB
14:47:11 [hello:30957]        (cap):     733.80 ms,  0.96 GB
14:47:12 [hello:30957]        setup:   2,353.48 ms,  1.21 GB
14:47:21 [hello:30957]     (clinit):     157.44 ms,  1.69 GB
14:47:21 [hello:30957]   (typeflow):   4,025.43 ms,  1.69 GB
14:47:21 [hello:30957]    (objects):   4,373.29 ms,  1.69 GB
14:47:21 [hello:30957]   (features):     219.18 ms,  1.69 GB
14:47:21 [hello:30957]     analysis:   8,954.62 ms,  1.69 GB
14:47:21 [hello:30957]     universe:     294.50 ms,  1.69 GB
14:47:22 [hello:30957]      (parse):     939.89 ms,  1.71 GB
14:47:24 [hello:30957]     (inline):   1,054.62 ms,  1.71 GB
14:47:26 [hello:30957]    (compile):   2,752.19 ms,  2.65 GB
14:47:26 [hello:30957]      compile:   4,831.85 ms,  2.65 GB
14:47:26 Fatal error:org.graalvm.compiler.debug.GraalError: com.oracle.svm.core.util.VMError$HostedError: missing implementation for runtime call: indexOf1Byte(byte[],int,int,byte)int
14:47:26 	at method: int java.lang.String.indexOf(int, int)  [Direct call from boolean RuntimePropertyParser.parseProperty(String)]
14:47:26 	at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:1014)
14:47:26 	at com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:945)
14:47:26 	at com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:263)
14:47:26 	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
14:47:26 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
14:47:26 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
14:47:26 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
14:47:26 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
14:47:26 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
14:47:26 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
14:47:26 Caused by: com.oracle.svm.core.util.VMError$HostedError: missing implementation for runtime call: indexOf1Byte(byte[],int,int,byte)int
14:47:26 	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
14:47:26 	at com.oracle.svm.core.graal.meta.SubstrateForeignCallsProvider.lookupForeignCall(SubstrateForeignCallsProvider.java:63)
14:47:26 	at com.oracle.svm.core.graal.meta.SubstrateForeignCallsProvider.getKilledLocations(SubstrateForeignCallsProvider.java:80)
14:47:26 	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.extended.ForeignCall.getKilledLocationIdentities(ForeignCall.java:60)
14:47:26 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.FloatingReadPhase$FloatingReadClosure.processCheckpoint(FloatingReadPhase.java:379)
14:47:26 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.FloatingReadPhase$FloatingReadClosure.processNode(FloatingReadPhase.java:335)
14:47:26 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.FloatingReadPhase$FloatingReadClosure.processNode(FloatingReadPhase.java:296)
14:47:26 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.graph.ReentrantNodeIterator.apply(ReentrantNodeIterator.java:119)
14:47:26 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.graph.ReentrantNodeIterator.apply(ReentrantNodeIterator.java:102)
14:47:26 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.FloatingReadPhase.run(FloatingReadPhase.java:228)
14:47:26 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
14:47:26 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:214)
14:47:26 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
14:47:26 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:209)
14:47:26 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:56)
14:47:26 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:38)
14:47:26 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:214)
14:47:26 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
14:47:26 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:209)
14:47:26 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:214)
14:47:26 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
14:47:26 	at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:226)
14:47:26 	at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:145)
14:47:26 	at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:130)
14:47:26 	at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:983)
14:47:26 	... 9 more
```

Uh uh....#ThisShouldNotBeHappeningNow

ideas?

**Comment by zakkak** [comment]
This is me toying around :)
Sorry
