### ISSUE TITLE
Build fail main (master) branch: ` cannot find symbol SpeculationReasonEncoding`

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel#146]
Hello,

October 10
----------
```

 0d53b7344d498167cf0b25f9a5e9b36bbb7b7775

    refs/remotes/origin/graal/master

GOOD
```

October 11
----------
```
 e238145ae8ff0dbfb41e33610b6f0d51c10879ad

    refs/remotes/origin/graal/master

FAIL
```
```
09:49:12 + export JAVA_VERSION=11.0.9-ea+6
09:49:12 + JAVA_VERSION=11.0.9-ea+6
09:49:12 + export MANDREL_HOME=/home/jenkins/jenkins/workspace/mandrel-master-linux-build/mandrel-java11-master
09:49:12 + MANDREL_HOME=/home/jenkins/jenkins/workspace/mandrel-master-linux-build/mandrel-java11-master
09:49:12 + popd
09:49:12 ~/jenkins/workspace/mandrel-master-linux-build
09:49:12 + /usr/java/openjdk-11.0.9_6/bin/java -ea build.java --maven-local-repository /home/jenkins/.m2/repository --mandrel-repo /home/jenkins/jenkins/workspace/mandrel-master-linux-build/mandrel --mx-home /home/jenkins/jenkins/workspace/mandrel-master-linux-build/mx --maven-home /opt/apache-maven-3.6.3 --mandrel-version master e238145ae8 --mandrel-home /home/jenkins/jenkins/workspace/mandrel-master-linux-build/mandrel-java11-master --archive-suffix tar.gz
09:49:13 INFO [build] Building!
09:49:20 Note: /home/jenkins/jenkins/workspace/mandrel-master-linux-build/mx/java/ListModules.java uses unchecked or unsafe operations.
09:49:20 Note: Recompile with -Xlint:unchecked for details.
09:49:56 Note: /home/jenkins/jenkins/workspace/mandrel-master-linux-build/mandrel/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JavaLangSubstitutions.java uses or overrides a deprecated API that is marked for removal.
09:49:56 Note: Recompile with -Xlint:removal for details.
09:50:01 /home/jenkins/jenkins/workspace/mandrel-master-linux-build/mandrel/substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/isolated/IsolatedSpeculationReason.java:41: error: cannot find symbol
09:50:01     public SpeculationLog.SpeculationReasonEncoding encode(Supplier<SpeculationLog.SpeculationReasonEncoding> encodingSupplier) {
09:50:01                                                                                   ^
09:50:01   symbol:   class SpeculationReasonEncoding
09:50:01   location: interface SpeculationLog
09:50:01 /home/jenkins/jenkins/workspace/mandrel-master-linux-build/mandrel/substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/isolated/IsolatedSpeculationReason.java:41: error: cannot find symbol
09:50:01     public SpeculationLog.SpeculationReasonEncoding encode(Supplier<SpeculationLog.SpeculationReasonEncoding> encodingSupplier) {
09:50:01                          ^
09:50:01   symbol:   class SpeculationReasonEncoding
09:50:01   location: interface SpeculationLog
09:50:01 /home/jenkins/jenkins/workspace/mandrel-master-linux-build/mandrel/substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/isolated/IsolatedSpeculationReasonEncoding.java:40: error: cannot find symbol
09:50:01 final class IsolatedSpeculationReasonEncoding extends ByteArrayOutputStream implements SpeculationLog.SpeculationReasonEncoding {
09:50:01                                                                                                      ^
09:50:01   symbol:   class SpeculationReasonEncoding
09:50:01   location: interface SpeculationLog
09:50:01 3 errors
09:50:01 
09:50:01 Compiling com.oracle.svm.graal with javac-daemon(JDK 11) failed
09:50:01 1 build tasks failed
09:50:01 Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed, exit code: 1
09:50:01  at OperatingSystem.exec(build.java:1466)
09:50:01  at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
09:50:01  at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
09:50:01  at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
09:50:01  at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
09:50:01  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
09:50:01  at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
09:50:01  at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
09:50:01  at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
09:50:01  at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
09:50:01  at Mx.build(build.java:563)
09:50:01  at SequentialBuild.build(build.java:398)
09:50:01  at build.main(build.java:56)
09:50:01 Caused by: java.lang.RuntimeException: Failed, exit code: 1
09:50:01  at OperatingSystem.exec(build.java:1457)
09:50:01  at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
09:50:01  at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
09:50:01  at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
09:50:01  at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
09:50:01  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
09:50:01  at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
09:50:01  at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
09:50:01  at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
09:50:01  at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
09:50:01  at Mx.build(build.java:563)
09:50:01  at SequentialBuild.build(build.java:398)
09:50:01  at build.main(build.java:56)
09:50:01  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:50:01  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09:50:01  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:50:01  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
09:50:01  at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:404)
09:50:01  at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:179)
09:50:01  at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:119)
```

**Comment by Karm** [comment]
@jerboaa Is this expected? I will update to 11.0.9+10 now.

**Comment by zakkak** [comment]
It looks like https://github.com/oracle/graal/commit/2d5eee064d2a9a6ec2e99c68c48ecfe9b8fc7e86 depends on https://bugs.openjdk.java.net/browse/JDK-8220623 (backported to labsJDK11 in https://github.com/graalvm/labs-openjdk-11/commit/fbbdf5f15300716110d2ac9b9bd7f70b03b35a7d).

**Comment by jerboaa** [comment]
As expected this fails with 11.0.9+10 too. @zakkak seems right. We probably need some conditional code to not use `SpeculationReasonEncoding` for OpenJDK-based graal VM (Mandrel).

**Comment by zakkak** [comment]
Pending on upstream: https://github.com/oracle/graal/pull/2945

**Comment by jerboaa** [comment]
https://github.com/oracle/graal/pull/2945 has been integrated. Closing.
