### ISSUE TITLE
Mandrel master, Error: No instances of java.awt.color.ICC_ColorSpace are allowed, Quarkus 1.7.5.Final,1.9.0.CR1

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel#148]
Hello,

Mandrel master `0d53b7344d498167cf0b25f9a5e9b36bbb7b7775, refs/remotes/origin/graal/master` fails to build the undermentioned Quarkus application and crashes on:

```
[INFO] --- quarkus-maven-plugin:1.9.0.CR1:native-image (default) @ quarkus-full-microprofile ---
[INFO] [org.jboss.threads] JBoss Threads version 3.1.1.Final
[INFO] [io.quarkus.smallrye.jwt.deployment.SmallRyeJwtProcessor] Adding META-INF/resources/publicKey.pem to native image
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: /tmp/reproducer/quarkus-full-microprofile/target/quarkus-native-image-source-jar/quarkus-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /tmp/reproducer/quarkus-full-microprofile/target/quarkus-native-image-source-jar/quarkus-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on Snapshot
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] /tmp/reproducer/mandrel-java11-master/bin/native-image -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Drx.unsafe-disable=true -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Duser.language=en -J-Dfile.encoding=UTF-8 -H:IncludeResources=privateKey.pem --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -jar quarkus-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:NativeLinkerOption=-no-pie -H:-UseServiceLoaderFeature -H:+StackTrace quarkus-runner
[quarkus-runner:15107]    classlist:   2,367.55 ms,  1.19 GB
[quarkus-runner:15107]        (cap):     589.86 ms,  1.19 GB
[quarkus-runner:15107]        setup:   2,262.36 ms,  1.18 GB
14:04:38,364 INFO  [org.jbo.res.res.i18n] RESTEASY002225: Deploying javax.ws.rs.core.Application: class com.example.quarkus.QuarkusRestApplication
14:04:55,974 INFO  [org.jbo.threads] JBoss Threads version 3.1.1.Final
[quarkus-runner:15107]     (clinit):     694.14 ms,  5.01 GB
[quarkus-runner:15107]   (typeflow):  16,543.42 ms,  5.01 GB
[quarkus-runner:15107]    (objects):  24,546.91 ms,  5.01 GB
[quarkus-runner:15107]   (features):     881.43 ms,  5.01 GB
[quarkus-runner:15107]     analysis:  43,994.28 ms,  5.01 GB
Error: No instances of java.awt.color.ICC_ColorSpace are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=java.awt.color.ICC_ColorSpace.
Detailed message:
Trace: Object was reached by 
	reading field javax.imageio.ImageTypeSpecifier.sRGB

com.oracle.svm.core.util.UserError$UserException: No instances of java.awt.color.ICC_ColorSpace are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=java.awt.color.ICC_ColorSpace.
Detailed message:
Trace: Object was reached by 
	reading field javax.imageio.ImageTypeSpecifier.sRGB

	at com.oracle.svm.core.util.UserError.abort(UserError.java:82)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:217)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:770)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:560)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:473)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.awt.color.ICC_ColorSpace are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=java.awt.color.ICC_ColorSpace.
Detailed message:
Trace: Object was reached by 
	reading field javax.imageio.ImageTypeSpecifier.sRGB

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:767)
	... 8 more
Error: Image build request failed with exit status 1
```

# Steps to reproduce

`tar -xf` [mandrel-java11-linux-amd64-master.tar.gz](https://ci.modcluster.io/view/Mandrel/job/mandrel-master-linux-build/107/artifact/mandrel-java11-linux-amd64-master.tar.gz)
`export JAVA_HOME=$(pwd)/mandrel-java11-master;export GRAALVM_HOME=${JAVA_HOME};export PATH=${JAVA_HOME}/bin:${PATH}`
`unzip` [quarkus-full-microprofile.zip](https://github.com/graalvm/mandrel/files/5371333/quarkus-full-microprofile.zip)
`cd quarkus-full-microprofile/`
`mvn clean compile package -Pnative`

**Comment by zakkak** [comment]
This needs to be fixed in Quarkus. 

Being tracked in https://github.com/quarkusio/quarkus/issues/12535

**Comment by Karm** [comment]
@zakkak I somehow managed to miss it. Thanks. Closing it here.
