### ISSUE TITLE
Quarkus HTTP tests fail with 20.3 in GH workflow

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#170]
## Description
`quarkus-integration-test-vertx-http` fails with:
```
2020-11-17T20:07:14.4162117Z 2020-11-17 20:07:14,272 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.nio.file.NoSuchFileException: server-keystore.jks
2020-11-17T20:07:14.4164305Z 	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
2020-11-17T20:07:14.4166070Z 	at java.nio.file.Files.newByteChannel(Files.java:370)
2020-11-17T20:07:14.4167316Z 	at java.nio.file.Files.newByteChannel(Files.java:421)
2020-11-17T20:07:14.4169583Z 	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
2020-11-17T20:07:14.4171155Z 	at java.nio.file.Files.newInputStream(Files.java:155)
2020-11-17T20:07:14.4172781Z 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.getFileContent(VertxHttpRecorder.java:657)
2020-11-17T20:07:14.4175129Z 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.createSslOptions(VertxHttpRecorder.java:586)
2020-11-17T20:07:14.4178807Z 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.doServerStart(VertxHttpRecorder.java:442)
2020-11-17T20:07:14.4182871Z 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.startServer(VertxHttpRecorder.java:231)
2020-11-17T20:07:14.4186847Z 	at io.quarkus.deployment.steps.VertxHttpProcessor$openSocket-2064782366.deploy_0(VertxHttpProcessor$openSocket-2064782366.zig:136)
2020-11-17T20:07:14.4190216Z 	at io.quarkus.deployment.steps.VertxHttpProcessor$openSocket-2064782366.deploy(VertxHttpProcessor$openSocket-2064782366.zig:40)
2020-11-17T20:07:14.4193136Z 	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:521)
2020-11-17T20:07:14.4195552Z 	at io.quarkus.runtime.Application.start(Application.java:90)
2020-11-17T20:07:14.4198814Z 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:96)
2020-11-17T20:07:14.4200517Z 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:62)
2020-11-17T20:07:14.4201476Z 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
2020-11-17T20:07:14.4203023Z 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:104)
2020-11-17T20:07:14.4204473Z 	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
```

`quarkus-integration-test-rest-client` fails with:
```
2020-11-17T21:00:36.9323420Z [ERROR] WARNING: An illegal reflective access operation has occurred
2020-11-17T21:00:36.9330933Z [ERROR] WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v9.Java9 (file:/home/runner/.m2/repository/org/codehaus/groovy/groovy/3.0.6/groovy-3.0.6.jar) to constructor java.lang.AssertionError(java.lang.String)
2020-11-17T21:00:36.9334291Z [ERROR] WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v9.Java9
2020-11-17T21:00:36.9337023Z [ERROR] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
2020-11-17T21:00:36.9343424Z [ERROR] WARNING: All illegal access operations will be denied in a future release
2020-11-17T21:00:36.9414777Z 2020-11-17 21:00:36,911 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-2) HTTP Request to /self-signed failed, error id: 0123564e-f840-4eed-86c4-7fb9625ab2f6-1: org.jboss.resteasy.spi.UnhandledException: javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2020-11-17T21:00:36.9420308Z 	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
2020-11-17T21:00:36.9423817Z 	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
2020-11-17T21:00:36.9427042Z 	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
2020-11-17T21:00:36.9430096Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
2020-11-17T21:00:36.9432671Z 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
2020-11-17T21:00:36.9436662Z 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
2020-11-17T21:00:36.9439946Z 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
2020-11-17T21:00:36.9448531Z 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
2020-11-17T21:00:36.9452409Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
2020-11-17T21:00:36.9456301Z 	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
2020-11-17T21:00:36.9459204Z 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:133)
2020-11-17T21:00:36.9462260Z 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:38)
2020-11-17T21:00:36.9465118Z 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:95)
2020-11-17T21:00:36.9467876Z 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
2020-11-17T21:00:36.9471145Z 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
2020-11-17T21:00:36.9473574Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
2020-11-17T21:00:36.9475525Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
2020-11-17T21:00:36.9477432Z 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2020-11-17T21:00:36.9479517Z 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2020-11-17T21:00:36.9482197Z 	at java.lang.Thread.run(Thread.java:834)
2020-11-17T21:00:36.9483346Z 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
2020-11-17T21:00:36.9485311Z 	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
2020-11-17T21:00:36.9507971Z 	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
2020-11-17T21:00:36.9516038Z Caused by: javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2020-11-17T21:00:36.9520812Z 	at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:287)
2020-11-17T21:00:36.9525018Z 	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:488)
2020-11-17T21:00:36.9528326Z 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:149)
2020-11-17T21:00:36.9567396Z 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112)
2020-11-17T21:00:36.9570071Z 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
2020-11-17T21:00:36.9571769Z 	at com.sun.proxy.$Proxy202.invoke(Unknown Source)
2020-11-17T21:00:36.9572665Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2020-11-17T21:00:36.9575317Z 	at org.jboss.resteasy.microprofile.client.InvocationContextImpl.interceptorChainCompleted(InvocationContextImpl.java:62)
2020-11-17T21:00:36.9579146Z 	at org.jboss.resteasy.microprofile.client.InvocationContextImpl.proceed(InvocationContextImpl.java:91)
2020-11-17T21:00:36.9582205Z 	at io.smallrye.faulttolerance.FaultToleranceInterceptor.lambda$syncFlow$5(FaultToleranceInterceptor.java:204)
2020-11-17T21:00:36.9584799Z 	at io.smallrye.faulttolerance.core.InvocationContext.call(InvocationContext.java:20)
2020-11-17T21:00:36.9586646Z 	at io.smallrye.faulttolerance.core.Invocation.apply(Invocation.java:24)
2020-11-17T21:00:36.9588321Z 	at io.smallrye.faulttolerance.core.retry.Retry.apply(Retry.java:79)
2020-11-17T21:00:36.9590637Z 	at io.smallrye.faulttolerance.core.GeneralMetricsRecorder.apply(GeneralMetricsRecorder.java:17)
2020-11-17T21:00:36.9596105Z 	at io.smallrye.faulttolerance.FaultToleranceInterceptor.syncFlow(FaultToleranceInterceptor.java:206)
2020-11-17T21:00:36.9599206Z 	at io.smallrye.faulttolerance.FaultToleranceInterceptor.interceptCommand(FaultToleranceInterceptor.java:159)
2020-11-17T21:00:36.9601941Z 	at io.smallrye.faulttolerance.FaultToleranceInterceptor_Bean.intercept(FaultToleranceInterceptor_Bean.zig:555)
2020-11-17T21:00:36.9604471Z 	at org.jboss.resteasy.microprofile.client.InvocationContextImpl$InterceptorInvocation.invoke(InvocationContextImpl.java:154)
2020-11-17T21:00:36.9672699Z 	at org.jboss.resteasy.microprofile.client.InvocationContextImpl.invokeNext(InvocationContextImpl.java:53)
2020-11-17T21:00:36.9678307Z 	at org.jboss.resteasy.microprofile.client.InvocationContextImpl.proceed(InvocationContextImpl.java:89)
2020-11-17T21:00:36.9683594Z 	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:144)
2020-11-17T21:00:36.9686623Z 	at com.sun.proxy.$Proxy203.invoke(Unknown Source)
2020-11-17T21:00:36.9688672Z 	at io.quarkus.it.rest.client.selfsigned.ExternalSelfSignedResource.perform(ExternalSelfSignedResource.java:29)
2020-11-17T21:00:36.9690970Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2020-11-17T21:00:36.9692495Z 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
2020-11-17T21:00:36.9695273Z 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
2020-11-17T21:00:36.9698008Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
2020-11-17T21:00:36.9701253Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
2020-11-17T21:00:36.9705185Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
2020-11-17T21:00:36.9709322Z 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
2020-11-17T21:00:36.9713306Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
2020-11-17T21:00:36.9717398Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
2020-11-17T21:00:36.9720749Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
2020-11-17T21:00:36.9723788Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
2020-11-17T21:00:36.9727246Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
2020-11-17T21:00:36.9728921Z 	... 19 more
2020-11-17T21:00:36.9731588Z Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2020-11-17T21:00:36.9733920Z 	at sun.security.ssl.Alert.createSSLException(Alert.java:131)
2020-11-17T21:00:36.9735277Z 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:350)
2020-11-17T21:00:36.9737444Z 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:293)
2020-11-17T21:00:36.9739021Z 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:288)
2020-11-17T21:00:36.9740885Z 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
2020-11-17T21:00:36.9743378Z 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
2020-11-17T21:00:36.9746482Z 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
2020-11-17T21:00:36.9756119Z 	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
2020-11-17T21:00:36.9757754Z 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
2020-11-17T21:00:36.9759423Z 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
2020-11-17T21:00:36.9761197Z 	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:183)
2020-11-17T21:00:36.9762735Z 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
2020-11-17T21:00:36.9764082Z 	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1408)
2020-11-17T21:00:36.9778318Z 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1314)
2020-11-17T21:00:36.9780307Z 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
2020-11-17T21:00:36.9782081Z 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
2020-11-17T21:00:36.9784712Z 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
2020-11-17T21:00:36.9788074Z 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
2020-11-17T21:00:36.9791721Z 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
2020-11-17T21:00:36.9796498Z 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
2020-11-17T21:00:36.9800535Z 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
2020-11-17T21:00:36.9803129Z 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
2020-11-17T21:00:36.9805159Z 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
2020-11-17T21:00:36.9807063Z 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
2020-11-17T21:00:36.9810664Z 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
2020-11-17T21:00:36.9812910Z 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
2020-11-17T21:00:36.9815180Z 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
2020-11-17T21:00:36.9818217Z 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
2020-11-17T21:00:36.9822852Z 	at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:268)
2020-11-17T21:00:36.9825820Z 	... 53 more
2020-11-17T21:00:36.9828637Z Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2020-11-17T21:00:36.9831751Z 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
2020-11-17T21:00:36.9834215Z 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
2020-11-17T21:00:36.9835900Z 	at sun.security.validator.Validator.validate(Validator.java:264)
2020-11-17T21:00:36.9837531Z 	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
2020-11-17T21:00:36.9839343Z 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
2020-11-17T21:00:36.9841450Z 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
2020-11-17T21:00:36.9843660Z 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
2020-11-17T21:00:36.9845015Z 	... 77 more
2020-11-17T21:00:36.9846496Z Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2020-11-17T21:00:36.9849338Z 	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
2020-11-17T21:00:36.9852672Z 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
2020-11-17T21:00:36.9854805Z 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
2020-11-17T21:00:36.9856365Z 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
2020-11-17T21:00:36.9857412Z 	... 83 more
2020-11-17T21:00:36.9857627Z 
2020-11-17T21:00:38.1436215Z 2020-11-17 21:00:38,120 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-2) HTTP Request to /self-signed/java failed, error id: 0123564e-f840-4eed-86c4-7fb9625ab2f6-2: org.jboss.resteasy.spi.UnhandledException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2020-11-17T21:00:38.1459295Z 	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
2020-11-17T21:00:38.1462025Z 	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
2020-11-17T21:00:38.1464629Z 	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
2020-11-17T21:00:38.1467066Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
2020-11-17T21:00:38.1510423Z 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
2020-11-17T21:00:38.1513259Z 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
2020-11-17T21:00:38.1518403Z 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
2020-11-17T21:00:38.1552080Z 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
2020-11-17T21:00:38.1554971Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
2020-11-17T21:00:38.1558210Z 	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
2020-11-17T21:00:38.1561387Z 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:133)
2020-11-17T21:00:38.1565051Z 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:38)
2020-11-17T21:00:38.1568135Z 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:95)
2020-11-17T21:00:38.1570780Z 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
2020-11-17T21:00:38.1573225Z 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
2020-11-17T21:00:38.1575252Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
2020-11-17T21:00:38.1577373Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
2020-11-17T21:00:38.1579057Z 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2020-11-17T21:00:38.1580987Z 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2020-11-17T21:00:38.1582532Z 	at java.lang.Thread.run(Thread.java:834)
2020-11-17T21:00:38.1583448Z 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
2020-11-17T21:00:38.1585138Z 	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
2020-11-17T21:00:38.1587701Z 	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
2020-11-17T21:00:38.1591147Z Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2020-11-17T21:00:38.1594544Z 	at sun.security.ssl.Alert.createSSLException(Alert.java:131)
2020-11-17T21:00:38.1596256Z 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:350)
2020-11-17T21:00:38.1597732Z 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:293)
2020-11-17T21:00:38.1599264Z 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:288)
2020-11-17T21:00:38.1602253Z 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
2020-11-17T21:00:38.1604624Z 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
2020-11-17T21:00:38.1607863Z 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
2020-11-17T21:00:38.1609593Z 	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
2020-11-17T21:00:38.1611077Z 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
2020-11-17T21:00:38.1619932Z 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
2020-11-17T21:00:38.1621541Z 	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:183)
2020-11-17T21:00:38.1623013Z 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
2020-11-17T21:00:38.1624330Z 	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1408)
2020-11-17T21:00:38.1625935Z 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1314)
2020-11-17T21:00:38.1627756Z 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
2020-11-17T21:00:38.1829782Z 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
2020-11-17T21:00:38.1831863Z 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
2020-11-17T21:00:38.1834669Z 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
2020-11-17T21:00:38.1839588Z 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
2020-11-17T21:00:38.1842286Z 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
2020-11-17T21:00:38.1847819Z 	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
2020-11-17T21:00:38.1850300Z 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
2020-11-17T21:00:38.1853617Z 	at io.quarkus.it.rest.client.selfsigned.ExternalSelfSignedResource.doGetCipher(ExternalSelfSignedResource.java:53)
2020-11-17T21:00:38.1862402Z 	at io.quarkus.it.rest.client.selfsigned.ExternalSelfSignedResource.invokeJavaURLWithDefaultTruststore(ExternalSelfSignedResource.java:44)
2020-11-17T21:00:38.1873234Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2020-11-17T21:00:38.1874682Z 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
2020-11-17T21:00:38.1876668Z 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
2020-11-17T21:00:38.1879304Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
2020-11-17T21:00:38.1883225Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
2020-11-17T21:00:38.1886656Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
2020-11-17T21:00:38.1891068Z 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
2020-11-17T21:00:38.1894806Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
2020-11-17T21:00:38.1897811Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
2020-11-17T21:00:38.1902729Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
2020-11-17T21:00:38.1907124Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
2020-11-17T21:00:38.1909605Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
2020-11-17T21:00:38.1910872Z 	... 19 more
2020-11-17T21:00:38.1914154Z Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2020-11-17T21:00:38.1918191Z 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
2020-11-17T21:00:38.1920735Z 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
2020-11-17T21:00:38.1922525Z 	at sun.security.validator.Validator.validate(Validator.java:264)
2020-11-17T21:00:38.1924187Z 	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
2020-11-17T21:00:38.1926063Z 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
2020-11-17T21:00:38.1928445Z 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
2020-11-17T21:00:38.1930682Z 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
2020-11-17T21:00:38.1932024Z 	... 50 more
2020-11-17T21:00:38.1933483Z Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2020-11-17T21:00:38.1935927Z 	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
2020-11-17T21:00:38.1938398Z 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
2020-11-17T21:00:38.1940519Z 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
2020-11-17T21:00:38.1942079Z 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
2020-11-17T21:00:38.1943048Z 	... 56 more
```

## How To Reproduce
I was **not** able to reproduce locally with:
1. Build `mandrel/20.3` using https://github.com/graalvm/mandrel-packaging
2. `git clone git@github.com:quarkusio/quarkus.git`
3. `cd quarkus`
3. `mvn -Dnative.surefire.skip -Dnative verify -pl integration-tests/vertx-http`
3. `mvn -Dnative.surefire.skip -Dnative verify -pl integration-tests/rest-easy`

### Configuration:
 - OS: Fedora 33
 - Architecture: AMD64
 - Mandrel version: `mandrel/20.3` branch
 - JDK version: OpenJDK 11.0.9+11

## Expected behavior
Tests should pass

**Comment by Karm** [comment]
@zakkak There were already debated [here](https://github.com/quarkusio/quarkus/issues/13275#issuecomment-726741225), weren't they?

**Comment by zakkak** [comment]
Yes, this is probably the same issue, but it is also kind of strange that in our GH workflow they seem to pass for 20.2 https://github.com/graalvm/mandrel/runs/1309439260#step:18:1111

**Comment by zakkak** [comment]
This no longer appears after merging https://github.com/graalvm/mandrel/pull/181
