### ISSUE TITLE
Mandrel fails to build with OpenJDK 11.0.11+1 EA build

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#210]
## Description
Mandrel fails to build with [OpenJDK 11.0.11+1 EA build](https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/tag/jdk-11.0.11%2B1)

The build fails with:
```
Could not find any unresolved JVM_* symbols in static JDK libraries
JvmFuncsFallbacksBuildTask svm-jvmfuncs-fallback-builder failed
1 build tasks failed
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1651)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at Mx.build(build.java:704)
	at SequentialBuild.build(build.java:517)
	at build.main(build.java:63)
Caused by: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1642)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at Mx.build(build.java:704)
	at SequentialBuild.build(build.java:517)
	at build.main(build.java:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:404)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:179)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:119)
```
(see https://github.com/graalvm/mandrel/runs/1834775399)

## How To Reproduce
```shell
wget "https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.11%2B1/OpenJDK11U-jdk_x64_linux_11.0.11_1_ea.tar.gz"
wget "https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.11%2B1/OpenJDK11U-static-libs_x64_linux_11.0.11_1_ea.tar.gz"
tar -C /tmp/jvm/ -xvf OpenJDK11U-jdk_x64_linux_11.0.11_1_ea.tar.gz 
tar -C /tmp/jvm/ -xvf OpenJDK11U-static-libs_x64_linux_11.0.11_1_ea.tar.gz
export JAVA_HOME=/tmp/jvm/openjdk-11.0.11_1
$JAVA_HOME/bin/java -ea /tmp/mandrel-packaging/build.java --mx-home /tmp/mx --mandrel-repo /tmp/mandrel
```

### Configuration:
 - OS: Fedora 33
 - Architecture: AMD64
 - Mandrel version: all
 - JDK version: OpenJDK 11.0.11+1

## Expected behavior
It should build

## Additional context
It looks like the static libraries are now under `lib/static/linux-amd64/glibc/lib/` instead of `lib/static/linux-amd64/glibc/` where they used to be.

**Comment by zakkak** [comment]
Fixed in https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/pull/20
