### ISSUE TITLE
Mandrel build failure with latest graal

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#225]
`graal/master` branch fails to build (both with OpenJDK 11 GA and EA).

The error log is:
```
Error: @RestrictHeapAccess warning: Restricted method: 'SubstrateUtil.printDiagnostics(Log, Pointer, CodePointer, RegisterDumper$Context)' calls 'VMOperationControl$VMOpHistory$$Lambda$ca91da068fbe395c2178d758d4d0702d388c9790.get$Lambda()' that violates restriction NO_ALLOCATION.
  [Path:
    app//com.oracle.svm.core.SubstrateUtil.printDiagnostics(SubstrateUtil.java:379)
    app//com.oracle.svm.core.SubstrateUtil.dumpRecentVMOperations(SubstrateUtil.java:563)
    app//com.oracle.svm.core.thread.VMOperationControl.logRecentEvents(VMOperationControl.java:212)
    app//com.oracle.svm.core.thread.VMOperationControl$VMOpHistory.print(VMOperationControl.java:886)
    com.oracle.svm.core.thread.VMOperationControl$VMOpHistory$$Lambda$ca91da068fbe395c2178d758d4d0702d388c9790.get$Lambda()]
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1664)
	at build.buildAgents(build.java:178)
	at build.main(build.java:161)
Caused by: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1655)
	at build.buildAgents(build.java:178)
	at build.main(build.java:161)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:404)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:179)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:119)
```

See: https://github.com/graalvm/mandrel/runs/2154085147?check_suite_focus=true

**Comment by zakkak** [comment]
The issue appears in the compile face of `native-image` when trying to build `native-image-agent-library`. 

The same happens when compiling HelloWorld.

Running `native-image -H:+ReportExceptionStackTraces HelloWorld` results in:

```
Error: @RestrictHeapAccess warning: Restricted method: 'GCImpl$CollectionVMOperation.operate(NativeVMOperationData)' calls 'VMOperationControl$VMOpHistory$$Lambda$ca91da068fbe395c2178d758d4d0702d388c9790.get$Lambda()' that violates restriction NO_ALLOCATION.
  [Path:
    app//com.oracle.svm.core.genscavenge.GCImpl$CollectionVMOperation.operate(GCImpl.java:1110)
    app//com.oracle.svm.core.genscavenge.GCImpl.access$200(GCImpl.java:97)
    app//com.oracle.svm.core.genscavenge.GCImpl.collectOperation(GCImpl.java:174)
    app//com.oracle.svm.core.genscavenge.ThreadLocalAllocation.disableAndFlushForAllThreads(ThreadLocalAllocation.java:282)
    app//com.oracle.svm.core.thread.VMOperation.guaranteeInProgress(VMOperation.java:133)
    app//com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.shouldNotReachHere(VMErrorSubstitutions.java:63)
    app//com.oracle.svm.core.jdk.VMErrorSubstitutions.shouldNotReachHere(VMErrorSubstitutions.java:104)
    app//com.oracle.svm.core.jdk.VMErrorSubstitutions.shutdown(VMErrorSubstitutions.java:111)
    app//com.oracle.svm.core.jdk.VMErrorSubstitutions.doShutdown(VMErrorSubstitutions.java:136)
    app//com.oracle.svm.core.SubstrateUtil.printDiagnostics(SubstrateUtil.java:304)
    app//com.oracle.svm.core.SubstrateUtil.printDiagnostics(SubstrateUtil.java:379)
    app//com.oracle.svm.core.SubstrateUtil.dumpRecentVMOperations(SubstrateUtil.java:563)
    app//com.oracle.svm.core.thread.VMOperationControl.logRecentEvents(VMOperationControl.java:212)
    app//com.oracle.svm.core.thread.VMOperationControl$VMOpHistory.print(VMOperationControl.java:886)
    com.oracle.svm.core.thread.VMOperationControl$VMOpHistory$$Lambda$ca91da068fbe395c2178d758d4d0702d388c9790.get$Lambda()]
com.oracle.svm.core.util.UserError$UserException: @RestrictHeapAccess warning: Restricted method: 'GCImpl$CollectionVMOperation.operate(NativeVMOperationData)' calls 'VMOperationControl$VMOpHistory$$Lambda$ca91da068fbe395c2178d758d4d0702d388c9790.get$Lambda()' that violates restriction NO_ALLOCATION.
  [Path:
    app//com.oracle.svm.core.genscavenge.GCImpl$CollectionVMOperation.operate(GCImpl.java:1110)
    app//com.oracle.svm.core.genscavenge.GCImpl.access$200(GCImpl.java:97)
    app//com.oracle.svm.core.genscavenge.GCImpl.collectOperation(GCImpl.java:174)
    app//com.oracle.svm.core.genscavenge.ThreadLocalAllocation.disableAndFlushForAllThreads(ThreadLocalAllocation.java:282)
    app//com.oracle.svm.core.thread.VMOperation.guaranteeInProgress(VMOperation.java:133)
    app//com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.shouldNotReachHere(VMErrorSubstitutions.java:63)
    app//com.oracle.svm.core.jdk.VMErrorSubstitutions.shouldNotReachHere(VMErrorSubstitutions.java:104)
    app//com.oracle.svm.core.jdk.VMErrorSubstitutions.shutdown(VMErrorSubstitutions.java:111)
    app//com.oracle.svm.core.jdk.VMErrorSubstitutions.doShutdown(VMErrorSubstitutions.java:136)
    app//com.oracle.svm.core.SubstrateUtil.printDiagnostics(SubstrateUtil.java:304)
    app//com.oracle.svm.core.SubstrateUtil.printDiagnostics(SubstrateUtil.java:379)
    app//com.oracle.svm.core.SubstrateUtil.dumpRecentVMOperations(SubstrateUtil.java:563)
    app//com.oracle.svm.core.thread.VMOperationControl.logRecentEvents(VMOperationControl.java:212)
    app//com.oracle.svm.core.thread.VMOperationControl$VMOpHistory.print(VMOperationControl.java:886)
    com.oracle.svm.core.thread.VMOperationControl$VMOpHistory$$Lambda$ca91da068fbe395c2178d758d4d0702d388c9790.get$Lambda()]
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.code.RestrictHeapAccessAnnotationChecker$RestrictHeapAccessWarningVisitor.postRestrictHeapAccessWarning(RestrictHeapAccessAnnotationChecker.java:201)
	at com.oracle.svm.hosted.code.RestrictHeapAccessAnnotationChecker$RestrictHeapAccessWarningVisitor.visitMethod(RestrictHeapAccessAnnotationChecker.java:144)
	at com.oracle.svm.hosted.code.RestrictHeapAccessAnnotationChecker.check(RestrictHeapAccessAnnotationChecker.java:77)
	at com.oracle.svm.hosted.code.CompileQueue.finish(CompileQueue.java:351)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:651)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:493)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1760)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1507)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1468)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1455)
	at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1947)
```

**Comment by zakkak** [comment]
The issue seems to be caused by https://github.com/oracle/graal/commit/aefd22d55e3aba56225dc10579441c9263d5125e

Reverting:
* 57961ead3c4
* 4ec0567f1a9
* c323ce752d3 
* 11467c9ad54 
* 2a9be929d7f 
* f726e400785

`git revert --no-commit 57961ead3c4 4ec0567f1a9 c323ce752d3 11467c9ad54 2a9be929d7f f726e400785`

makes mandrel build again :eyes:
