### ISSUE TITLE
Native native-image not working without `-J--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=jdk.internal.vm.compiler`

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#234]
## Description
The **native** `native-image` generated by `native-image --macro:native-image-launcher` requires `-J--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=jdk.internal.vm.compiler` to work.

## How To Reproduce
```
export JAVA_HOME=/opt/jvms/openjdk-11.0.10_9
$JAVA_HOME/bin/java -ea build.java --mx-home ~/code/mx --mandrel-repo ~/code/graal --mandrel-home /tmp/graal-master
/tmp/graal-master/bin/native-image HelloWorld                                          # <--- Works
/tmp/graal-master/bin/native-image --macro:native-image-launcher 
/tmp/graal-master/bin/native-image HelloWorld                                          # <--- Doesn't work
```

### Configuration:
 - OS: Fedora 33
 - Architecture: AMD64
 - Mandrel version: 20.3 and 21.0
 - JDK version: OpenJDK 11.0.10+9

## Expected behavior
`native-image` should work either as a binary or a bash-script without additional flags

## Additional context
The ouput on failure is
```
Exception in thread "main" java.lang.IllegalAccessError: superinterface check failed: class org.graalvm.compiler.core.common.spi.ForeignCallsProvider (in module jdk.internal.vm.compiler) cannot access class jdk.vm.ci.code.ValueKindFactory (in module jdk.internal.vm.ci) because module jdk.internal.vm.ci does not export jdk.vm.ci.code to module jdk.internal.vm.compiler
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1096)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:206)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:759)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:680)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:605)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:640)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:609)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.installNativeImageClassLoader(NativeImageGeneratorRunner.java:175)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:578)
```

**Comment by jerboaa** [comment]
This is fixed in OpenJDK head with [JDK-8223332](https://bugs.openjdk.java.net/browse/JDK-8223332). This line:
http://hg.openjdk.java.net/jdk/jdk/rev/2d012a75d35c#l24.15

A partial backport of that large patch to OpenJDK 11u should be considered.

**Comment by jerboaa** [comment]
This is being tracked in OpenJDK via:
https://bugs.openjdk.java.net/browse/JDK-8273547

**Comment by jerboaa** [comment]
> This is being tracked in OpenJDK via:
> https://bugs.openjdk.java.net/browse/JDK-8273547

--^  should be in 11.0.14 (January 2022) release.

**Comment by zakkak** [comment]
This is now fixed, thanks @jerboaa !

```
$ ./mandrel-java11-22.0.0.2-Final-native/bin/native-image --macro:native-image-launcher
...
Finished generating 'native-image' in 1m 24s.

$ file ./mandrel-java11-22.0.0.2-Final-native/lib/svm/bin/native-image
./mandrel-java11-22.0.0.2-Final-native/lib/svm/bin/native-image: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=3e9091823cdd62eea1bd98fdd335fd3083148a0c, for GNU/Linux 3.2.0, with debug_info, not stripped

$ ./mandrel-java11-22.0.0.2-Final-native/lib/svm/bin/native-image --version
GraalVM 22.0.0.2 Java 11 Mandrel Distribution (Java Version 11.0.14+9)
```
