### ISSUE TITLE
Frequent Deadlock when compiling a specific snippet with --initialize-at-build-time=

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel#249]
# Steps to reproduce

Main.java
```
import java.awt.Font;
import java.awt.GraphicsEnvironment;

public class Main {
    public static void main(String[] args) {
        for (Font font : GraphicsEnvironment.getLocalGraphicsEnvironment().getAllFonts()) {
            System.out.printf("%s, %s\n", font.getFontName(), font.getFamily());
        }
    }
}
```

```
mkdir /tmp/rep
cd /tmp/rep
export JAVA_HOME=/home/karm/workspaceRH/mandrel-release/mandrel-java11-21.1.0.0-Final/;export GRAALVM_HOME=${JAVA_HOME};export PATH=${JAVA_HOME}/bin:${PATH}
javac Main.java
java -agentlib:native-image-agent=config-output-dir=./META-INF/native-image Main
```

Works :heavy_check_mark: 
```
native-image --no-fallback -H:DeadlockWatchdogInterval=1 Main
```

Deadlocks :x: 
```
native-image --no-fallback --initialize-at-build-time=  -H:DeadlockWatchdogInterval=1 Main
```
See deadlock: https://gist.github.com/Karm/08184eb1e2f75bbe911f824506e16392

UnsatisfiedLinkError :x:
When it doesn't deadlock and compiles, the resulting binary does not work and end up with:

```
Exception in thread "main" java.lang.InternalError: java.lang.reflect.InvocationTargetException
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:86)
	at java.security.AccessController.doPrivileged(AccessController.java:82)
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at sun.java2d.SunGraphicsEnvironment.getFontManagerForSGE(SunGraphicsEnvironment.java:189)
	at sun.java2d.SunGraphicsEnvironment.getAllFonts(SunGraphicsEnvironment.java:208)
	at sun.java2d.HeadlessGraphicsEnvironment.getAllFonts(HeadlessGraphicsEnvironment.java:72)
	at Main.main(Main.java:6)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:84)
	... 6 more
Caused by: java.lang.UnsatisfiedLinkError: sun.font.FontConfigManager.getFontConfigVersion()I [symbol: Java_sun_font_FontConfigManager_getFontConfigVersion or Java_sun_font_FontConfigManager_getFontConfigVersion__]
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:153)
	at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
	at sun.font.FontConfigManager.getFontConfigVersion(FontConfigManager.java)
	at sun.font.FcFontConfiguration.readFcInfo(FcFontConfiguration.java:455)
	at sun.font.FcFontConfiguration.init(FcFontConfiguration.java:192)
	at sun.font.FcFontConfiguration.<init>(FcFontConfiguration.java:76)
	at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:713)
	at sun.font.SunFontManager$2.run(SunFontManager.java:379)
	at java.security.AccessController.doPrivileged(AccessController.java:82)
	at sun.font.SunFontManager.<init>(SunFontManager.java:324)
	at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at sun.awt.X11FontManager.<init>(X11FontManager.java:56)
	... 8 more
```

Note the `-H:DeadlockWatchdogInterval=1` is just for convenience. It is 100% reproducible without it.

# Volumes
On my system, the issue is always reproducible on my root / volume in /tmp (xfs not tmpfs) and it sometimes passes on my second volume /home/.....   No idea if it's related to some I/O shenanigans. 

# GraalVM distro
I cannot reproduce it with GraalVM CE distro, the same example as above but for 
```
export JAVA_HOME=/var/X/JDKs/graalvm-ce-java11-21.1.0;export GRAALVM_HOME=${JAVA_HOME};export PATH=${JAVA_HOME}/bin:${PATH}
```
compiles just fine.

# Ubuntu 20
I cannot reproduce the issue on Ubuntu 20 VM. 
* gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
* kernel  5.8.0-44-generic #50~20.04.1-Ubuntu

## Stats
100% runs no deadlock.
```
grep -c "setup:" log.log
34
grep -c "Image build request failed" log.log
0
grep -c "write:" log.log
34
```

# My system
* Centos 8, kernel 4.18.0-240.15.1.el8_3.x86_64
* gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)

## Stats
50% runs no deadlock.
```
grep -c "setup:" log.log
26
grep -c "Image build request failed" log.log
13
grep -c "write:" log.log
13
```

See the log for deadlocks details: 
[deadlocks.log](https://github.com/graalvm/mandrel/files/6466834/deadlocks.log), namely `com.oracle.graal.pointsto.flow.MethodTypeFlow`.

**Comment by Karm** [comment]
@jerboaa Does it happen on your system too?

**Comment by jerboaa** [comment]
I'll have a look and will report back.

**Comment by Karm** [comment]
For the record, verbose log output from my Centos 8 workstation:

* [Deadlocked run](https://gist.github.com/Karm/47da0b3bbfd4e16136b7f7df4b81bd62)
* [Passing run](https://gist.github.com/Karm/de61828d895ddb6e9321054a8bde93ea)

**Comment by Karm** [comment]
As to the `UnsatisfiedLinkError`:

This is where the two binaries differ in their flow according to the strace:

With `--initialize-at-build-time= ` :x:

```
stat("/home/karm/.java/fonts/11.0.11/fcinfo-1-localhost.localdomain-RedHat-8.3.2011-en.properties", {st_mode=S_IFREG|0600, st_size=46286, ...}) = 0
openat(AT_FDCWD, "/home/karm/.java/fonts/11.0.11/fcinfo-1-localhost.localdomain-RedHat-8.3.2011-en.properties", O_RDONLY) = 9
fstat(9, {st_mode=S_IFREG|0600, st_size=46286, ...}) = 0
read(9, "#JDK Font Configuration Generate"..., 8192) = 8192
read(9, ".1.29.family=Nuosu SIL\nsansserif"..., 8192) = 8192
read(9, "amily=Padauk\nsansserif.3.20.file"..., 8192) = 8192
read(9, "paced.1.2.family=Nimbus Mono PS\n"..., 8192) = 8192
read(9, "r/share/fonts/sil-nuosu/NuosuSIL"..., 8192) = 8192
read(9, "f\nmonospaced.0.0.family=DejaVu S"..., 8192) = 5326
read(9, "", 8192)                       = 0
read(9, "", 8192)                       = 0
close(9)                                = 0
write(2, "Exception in thread \"main\" ", 27Exception in thread "main" ) = 27
write(2, "java.lang.InternalError: java.la"..., 68java.lang.InternalError: java.lang.reflect.InvocationTargetException) = 68
write(2, "\n", 1
)                       = 1
write(2, "\tat sun.font.FontManagerFactory$"..., 65 at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:86)) = 65

```


Without  `--initialize-at-build-time= ` :heavy_check_mark: 

```
stat("/home/karm/.java/fonts/11.0.11/fcinfo-1-localhost.localdomain-RedHat-8.3.2011-en.properties", {st_mode=S_IFREG|0600, st_size=46286, ...}) = 0
stat("/usr/lib/fontconfig/cache", {st_mode=S_IFDIR|0755, st_size=8192, ...}) = 0
stat("/usr/lib/fontconfig/cache", {st_mode=S_IFDIR|0755, st_size=8192, ...}) = 0
stat("/home/karm/.cache/fontconfig", {st_mode=S_IFDIR|0755, st_size=16384, ...}) = 0
stat("/home/karm/.cache/fontconfig", {st_mode=S_IFDIR|0755, st_size=16384, ...}) = 0
stat("/home/karm/.fontconfig", 0x7fffdb401790) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/fonts/gnu-free/FreeSerif.ttf", O_RDONLY) = 10
```

**Comment by Karm** [comment]
Hmm, it seems neither libawt_xawt.a nor libawt_headless.a are linked properly :-( , so 
```
JNIEXPORT jint JNICALL
Java_sun_font_FontConfigManager_getFontConfigVersion
    (JNIEnv *env, jclass obj) {
```
in fontpath.c is never found.

**Comment by Karm** [comment]
With 
```
--- a/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationAwt.java
+++ b/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationAwt.java
@@ -100,6 +100,8 @@ public class JNIRegistrationAwt extends JNIRegistrationUtil implements Feature {
 
         NativeLibrarySupport.singleton().preregisterUninitializedBuiltinLibrary("awt");
         nativeLibraries.addStaticJniLibrary("awt");
+///lib64/libfontconfig.so
+        nativeLibraries.addDynamicNonJniLibrary("fontconfig");
 
         if (isHeadless()) {
             NativeLibrarySupport.singleton().preregisterUninitializedBuiltinLibrary("awt_headless");
```

A slight move: https://editor.mergely.com/gsdcWroP/

**Comment by Karm** [comment]
# FIxed UnsatisfiedLinkError :heavy_check_mark: :fireworks: 

...and for some reason, it seems to fix the deadlock for me too. I need to test that more thoroughly though. 

**Patch:**
```
diff --git a/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationAwt.java b/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationAwt.java
index dd434171f8b..35d65a2c0e4 100644
--- a/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationAwt.java
+++ b/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationAwt.java
@@ -61,7 +61,8 @@ public class JNIRegistrationAwt extends JNIRegistrationUtil implements Feature {
                             clazz(access, "sun.java2d.Disposer"));
 
             access.registerReachabilityHandler(JNIRegistrationAwt::registerFreeType,
-                            clazz(access, "sun.font.FontManagerNativeLibrary"));
+                            clazz(access, "sun.font.FontManagerNativeLibrary"),
+                            clazz(access,"sun.font.FontConfigManager"));
 
             access.registerReachabilityHandler(JNIRegistrationAwt::registerLCMS,
                             clazz(access, "sun.java2d.cmm.lcms.LCMS"));
```

**Comment by Karm** [comment]
FYI @jerboaa @zakkak ^^^

**Comment by zakkak** [comment]
Nice! 

> Missing ../mandrel-java11-21.1-SNAPSHOT/lib/libawt_xawt.a ?
> 
> When I enforce that the jdk is _not_ headless in JNIRegistrationAwt, _xawt gets linked, but it blows up later during linking on duplicate `awt_LoadLibrary.c:(.text.AWTIsHeadless+0x0): multiple definition of AWTIsHeadless`.

You might find this interesting https://github.com/kkriske/graal/blob/08c7b3d71614cabb41ea58708786a839f9f06658/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/snippets/SubstrateGraphBuilderPlugins.java#L1034-L1051

Regarding the UnsatisfiedLInkError, I see that it has been mentioned before in https://github.com/oracle/graal/issues/2729, I suggest opening a PR upstream with the oneline patch.

**Comment by Karm** [comment]
@zakkak I am testing it with Graal master and I will have a PR presently...

**Comment by Karm** [comment]
@zakkak Since this is not Mandrel specific after all, I opened it in the Graal repo: https://github.com/oracle/graal/pull/3417

**Comment by zakkak** [comment]
Closing as `wontfix`, see https://github.com/oracle/graal/pull/3417 for details.
