### ISSUE TITLE
Quarkus jpa-oracle integration test fails to build

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#252]
## Description
Quarkus jpa-oracle integration test fails with Mandrel build from Graal head.

## How To Reproduce
1. `git clone https://github.com/graalvm/mandrel --branch graal/master`
2. `git clone https://github.com/graalvm/mandrel-packaging`
2. `git clone https://github.com/graalvm/mx`
3. `java -ea ./mandrel-packaging/build.java --mx-home mx --mandrel-repo mandrel --mandrel-home /tmp/mandrel
4. `export GRAALVM_HOME=/tmp/mandrel`
3. `./mvnw clean verify -Dnative -Dnative.surefire.skip -pl integration-tests/jpa-oracle`

### Configuration:
 - OS: Fedora 34
 - Architecture: AMD64
 - Mandrel version: 20.3, 21.1, graal/master
 - JDK version: 11.0.11+9

## Expected behavior
Test should build and pass as it does with the GraalVM CE.

## Additional context
Build fails with:
```
[quarkus-integration-test-jpa-oracle-999-SNAPSHOT-runner:549010]    classlist:   5,856.40 ms,  1.19 GB
[quarkus-integration-test-jpa-oracle-999-SNAPSHOT-runner:549010]        (cap):     616.74 ms,  1.19 GB
WARNING: Method java.sql.SQLXML.<init>() not found.
[quarkus-integration-test-jpa-oracle-999-SNAPSHOT-runner:549010]        setup:   3,448.04 ms,  1.19 GB
17:35:59,499 INFO  [org.hib.Version] HHH000412: Hibernate ORM core version 5.5.0.Alpha1
17:35:59,515 INFO  [org.hib.ann.com.Version] HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
17:35:59,553 INFO  [org.hib.dia.Dialect] HHH000400: Using dialect: org.hibernate.dialect.Oracle12cDialect
[quarkus-integration-test-jpa-oracle-999-SNAPSHOT-runner:549010]     analysis:  19,168.85 ms,  1.95 GB
Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing oracle.jdbc.driver.NoSupportHAManager.getInstance() 
Parsing context:
	parsing oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:783)
	parsing oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:919)
	parsing oracle.jdbc.driver.T2CConnection.<init>(T2CConnection.java:251)
	parsing oracle.jdbc.driver.T2CDriverExtension.getConnection(T2CDriverExtension.java:82)
	parsing oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:681)
	parsing oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:602)
	parsing com.oracle.svm.reflect.OracleDriver_connect_8af0cff7e696a994e201c11f0784956ffac49905_149.invoke(Unknown Source)
	parsing java.base@11.0.11/java.lang.reflect.Method.invoke(Method.java:566)
	parsing app//com.oracle.svm.core.containers.Metrics.systemMetrics(Metrics.java:62)
	parsing app//com.oracle.svm.core.containers.Container.metrics(Container.java:44)
	parsing app//com.oracle.svm.core.ContainerInfo.<init>(ContainerInfo.java:34)
	parsing app//com.oracle.svm.core.Containers.memoryLimitInBytes(Containers.java:162)
	parsing app//com.oracle.svm.core.heap.PhysicalMemory.doInitialize(PhysicalMemory.java:146)
	parsing app//com.oracle.svm.core.heap.PhysicalMemory.tryInitialize(PhysicalMemory.java:115)
	parsing app//com.oracle.svm.core.genscavenge.HeapPolicy.samplePhysicalMemorySize(HeapPolicy.java:364)
	parsing app//com.oracle.svm.core.genscavenge.ThreadLocalAllocation.runSlowPathHooks(ThreadLocalAllocation.java:161)
	parsing app//com.oracle.svm.core.genscavenge.ThreadLocalAllocation.slowPathNewArray(ThreadLocalAllocation.java:199)

	at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:327)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureTypeFlowCreated(MethodTypeFlow.java:302)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
	at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:420)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:547)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: org.graalvm.compiler.debug.GraalError: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.NoClassDefFoundError
	at parsing oracle.jdbc.driver.HAManager.<init>(HAManager.java:86)
	at parsing oracle.jdbc.driver.NoSupportHAManager.<init>(NoSupportHAManager.java:42)
	at parsing oracle.jdbc.driver.NoSupportHAManager.<clinit>(NoSupportHAManager.java:40)
	at parsing oracle.jdbc.driver.NoSupportHAManager.getInstance(NoSupportHAManager.java:46)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2585)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:106)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3439)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3242)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1119)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1013)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:76)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:113)
	at com.oracle.svm.hosted.SVMHost.parseBytecode(SVMHost.java:658)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:592)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:163)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:304)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:313)
	... 11 more
Caused by: org.graalvm.compiler.debug.GraalError: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.NoClassDefFoundError
	at parsing oracle.jdbc.driver.HAManager.<init>(HAManager.java:86)
	at parsing oracle.jdbc.driver.NoSupportHAManager.<init>(NoSupportHAManager.java:42)
	at parsing oracle.jdbc.driver.NoSupportHAManager.<clinit>(NoSupportHAManager.java:40)
	at com.oracle.graal.pointsto.util.AnalysisFuture.setException(AnalysisFuture.java:49)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:64)
	at com.oracle.graal.pointsto.meta.AnalysisType.ensureInitialized(AnalysisType.java:600)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:371)
	at com.oracle.graal.pointsto.infrastructure.AnalysisConstantPool.lookupField(AnalysisConstantPool.java:51)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.lookupField(BytecodeParser.java:4342)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genGetStatic(BytecodeParser.java:4887)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5390)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3434)
	... 26 more
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.NoClassDefFoundError
	at parsing oracle.jdbc.driver.HAManager.<init>(HAManager.java:86)
	at parsing oracle.jdbc.driver.NoSupportHAManager.<init>(NoSupportHAManager.java:42)
	at parsing oracle.jdbc.driver.NoSupportHAManager.<clinit>(NoSupportHAManager.java:40)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2585)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:106)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3439)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3242)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1119)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.parseAndInlineCallee(BytecodeParser.java:2607)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.inline(BytecodeParser.java:2505)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.tryInline(BytecodeParser.java:2248)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1903)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeSpecial(BytecodeParser.java:1787)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeSpecial(BytecodeParser.java:1779)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5395)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3434)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3242)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1119)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.parseAndInlineCallee(BytecodeParser.java:2607)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.inline(BytecodeParser.java:2505)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.tryInline(BytecodeParser.java:2248)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1903)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeSpecial(BytecodeParser.java:1787)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeSpecial(BytecodeParser.java:1779)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5395)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3434)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3242)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1119)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1013)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:76)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
	at com.oracle.svm.hosted.substitute.UnsafeAutomaticSubstitutionProcessor.getStaticInitializerGraph(UnsafeAutomaticSubstitutionProcessor.java:1086)
	at com.oracle.svm.hosted.substitute.UnsafeAutomaticSubstitutionProcessor.computeSubstitutions(UnsafeAutomaticSubstitutionProcessor.java:374)
	at com.oracle.svm.hosted.SVMHost.initializeType(SVMHost.java:292)
	at com.oracle.graal.pointsto.meta.AnalysisType.lambda$new$0(AnalysisType.java:228)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 34 more
Caused by: java.lang.NoClassDefFoundError
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.lookupType(HotSpotJVMCIRuntime.java:464)
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.lookupType(HotSpotResolvedObjectTypeImpl.java:977)
	at jdk.internal.vm.ci/jdk.vm.ci.meta.UnresolvedJavaType.resolve(UnresolvedJavaType.java:90)
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotResolvedJavaFieldImpl.getType(HotSpotResolvedJavaFieldImpl.java:128)
	at jdk.internal.vm.ci/jdk.vm.ci.meta.JavaField.getJavaKind(JavaField.java:49)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genPutField(BytecodeParser.java:4857)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genPutField(BytecodeParser.java:4853)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5393)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3434)
	... 68 more
Caused by: java.lang.ClassNotFoundException: oracle.simplefan.FanManager
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.CompilerToVM.lookupType(Native Method)
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.lookupType(HotSpotJVMCIRuntime.java:456)
	... 76 more
Error: Image build request failed with exit status 1
```

The corresponding GraalVM CE build works.

**Comment by zakkak** [comment]
Patching Quarkus with:
```diff
diff --git a/bom/application/pom.xml b/bom/application/pom.xml
index b80a9d3893..8cecf9b010 100644
--- a/bom/application/pom.xml
+++ b/bom/application/pom.xml
@@ -4333,6 +4333,11 @@
                 <artifactId>ojdbc8</artifactId>
                 <version>${oracle-jdbc.version}</version>
             </dependency>
+            <dependency>
+                <groupId>com.oracle.database.ha</groupId>
+                <artifactId>simplefan</artifactId>
+                <version>${oracle-jdbc.version}</version>
+            </dependency>
             <dependency>
                 <groupId>org.elasticsearch.client</groupId>
                 <artifactId>elasticsearch-rest-client</artifactId>
diff --git a/extensions/jdbc/jdbc-oracle/runtime/pom.xml b/extensions/jdbc/jdbc-oracle/runtime/pom.xml
index 9d56502238..89152b3ec2 100644
--- a/extensions/jdbc/jdbc-oracle/runtime/pom.xml
+++ b/extensions/jdbc/jdbc-oracle/runtime/pom.xml
@@ -26,6 +26,10 @@
             <groupId>com.oracle.database.jdbc</groupId>
             <artifactId>ojdbc8</artifactId>
         </dependency>
+        <dependency>
+            <groupId>com.oracle.database.ha</groupId>
+            <artifactId>simplefan</artifactId>
+        </dependency>
         <dependency>
             <groupId>org.graalvm.nativeimage</groupId>
             <artifactId>svm</artifactId>
```
Makes the test build, but we still need to figure out why this is needed in Mandrel and not in GraalVM builds.

**Comment by zakkak** [comment]
Patching Quarkus with:
```diff
diff --git a/bom/application/pom.xml b/bom/application/pom.xml
index b80a9d3893..8cecf9b010 100644
--- a/bom/application/pom.xml
+++ b/bom/application/pom.xml
@@ -4333,6 +4333,11 @@
                 <artifactId>ojdbc8</artifactId>
                 <version>${oracle-jdbc.version}</version>
             </dependency>
+            <dependency>
+                <groupId>com.oracle.database.ha</groupId>
+                <artifactId>simplefan</artifactId>
+                <version>${oracle-jdbc.version}</version>
+            </dependency>
             <dependency>
                 <groupId>org.elasticsearch.client</groupId>
                 <artifactId>elasticsearch-rest-client</artifactId>
diff --git a/extensions/jdbc/jdbc-oracle/runtime/pom.xml b/extensions/jdbc/jdbc-oracle/runtime/pom.xml
index 9d56502238..89152b3ec2 100644
--- a/extensions/jdbc/jdbc-oracle/runtime/pom.xml
+++ b/extensions/jdbc/jdbc-oracle/runtime/pom.xml
@@ -26,6 +26,10 @@
             <groupId>com.oracle.database.jdbc</groupId>
             <artifactId>ojdbc8</artifactId>
         </dependency>
+        <dependency>
+            <groupId>com.oracle.database.ha</groupId>
+            <artifactId>simplefan</artifactId>
+        </dependency>
         <dependency>
             <groupId>org.graalvm.nativeimage</groupId>
             <artifactId>svm</artifactId>
```
Makes the test build, but we still need to figure out why this is needed in Mandrel and not in GraalVM builds.

**Comment by zakkak** [comment]
@jerboaa this looks like a labs vs upstream OpenJDK issue to me.
I have tested it with a "mandrel build" based on labs OpenJDK and it works:
```
$ export JAVA_HOME=/opt/jvms/labsjdk-ce-11-jvmci-21.1-b02; $JAVA_HOME/bin/java -ea build.java --mx-home ~/code/mx --mandrel-repo ~/code/graal --mandrel-home /tmp/labs-mandrel --skip-clean
$ /tmp/labs-mandrel/bin/native-image --version
native-image 21.1.0 (Mandrel Distribution) (Java Version 11.0.11+5-jvmci-21.1-b02)
$ /tmp/labs-mandrel/bin/native-image -cp ~/.m2/repository/com/oracle/database/jdbc/ojdbc8/21.1.0.0/ojdbc8-21.1.0.0.jar:. Main 
[main:664929]    classlist:   1,431.70 ms,  0.96 GB
[main:664929]        (cap):     398.81 ms,  0.96 GB
WARNING: Method java.sql.SQLXML.<init>() not found.
[main:664929]        setup:   2,095.74 ms,  0.96 GB
[main:664929]     (clinit):     679.95 ms,  4.74 GB
[main:664929]   (typeflow):  18,709.09 ms,  4.74 GB
[main:664929]    (objects):  23,807.10 ms,  4.74 GB
[main:664929]   (features):   1,799.33 ms,  4.74 GB
[main:664929]     analysis:  46,275.66 ms,  4.74 GB
[main:664929]     universe:   2,044.19 ms,  5.20 GB
[main:664929]      (parse):   7,719.61 ms,  5.20 GB
[main:664929]     (inline):   7,786.02 ms,  5.91 GB
[main:664929]    (compile):  41,347.99 ms,  6.15 GB
[main:664929]      compile:  59,026.30 ms,  6.15 GB
[main:664929]        image:   4,954.18 ms,  6.15 GB
[main:664929]        write:     702.84 ms,  6.15 GB
# Printing build artifacts to: main.build_artifacts.txt
[main:664929]      [total]: 126,379.20 ms,  6.15 GB
```
 If you have any clue please let me know.

**Comment by jerboaa** [comment]
@zakkak I'll put it on my plate of things to look at :) Thanks for the heads-up.

**Comment by jerboaa** [comment]
This seems to be reproducible with mandrel 21.1.0.0-Final too (without the workaround in https://github.com/quarkusio/quarkus/commit/cf44a680e4de6f2335c2dc6dd284267c7ef5cadc obviously).

**Comment by jerboaa** [comment]
It's also not reproducible with a JDK 16-based graal vm build, which suggests a JVMCI level difference.

Looks to be issues due to an incomplete class path a la:

https://github.com/quarkusio/quarkus/issues/8081
https://github.com/graalvm/mandrel/issues/147
https://github.com/apache/camel-quarkus/issues/1161
https://github.com/quarkusio/quarkus/pull/8185

Seems the best fixes for those kinds of issues are https://github.com/quarkusio/quarkus/commit/cf44a680e4de6f2335c2dc6dd284267c7ef5cadc or what you've mentioned in https://github.com/graalvm/mandrel/issues/252#issuecomment-840399287 barring a JDK level upgrade (JDK 17?) which will upgrade the JVMCI level too.

**Comment by jerboaa** [comment]
@zakkak We won't update the OpenJDK 11 JVMCI level as it's too risky, so I'm inclined to close this one as won't fix. Thoughts?

**Comment by zakkak** [comment]
+1

Thanks for the summary @jerboaa !
