### ISSUE TITLE
JDK17: Nashorn engine is removed in JDK and Mandrel build must be edited

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel#280]
Mandrel build with the latest JDK 17 (head [db92c1bb5f3ff0b5](https://github.com/openjdk/jdk17u/commit/db92c1bb5f3ff0b5)) and also with JDK 18 (head [148935279d](https://github.com/openjdk/jdk/commit/148935279d)) requires removal of Nashorn engine feature: 

```
DEBUG [build] Patch native image...
DEBUG [build] mandrelVersion: 21.3.0-devd58f689da739
DEBUG [build] Launcher line BEFORE: exec "${location}/../../../bin/java" -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI --upgrade-module-path ${location}/../../jvmci/graal.jar --add-modules org.graalvm.truffle,org.graalvm.sdk --module-path ${location}/../../truffle/truffle-api.jar:${location}/../../jvmci/graal-sdk.jar "${jvm_args[@]}" ${app_path_arg} "${cp_or_mp}" ${main_class} "${launcher_args[@]}"
DEBUG [build] launcherMatcher.group(1): exec "${location}/../../../bin/java" -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI
DEBUG [build] launcherMatcher.group(2):  --upgrade-module-path ${location}/../../jvmci/graal.jar --add-modules org.graalvm.truffle,org.graalvm.sdk --module-path ${location}/../../truffle/truffle-api.jar:${location}/../../jvmci/graal-sdk.jar "${jvm_args[@]}" ${app_path_arg} "${cp_or_mp}" ${main_class} "${launcher_args[@]}"
DEBUG [build] Launcher line AFTER: exec "${location}/../../../bin/java" -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -Dorg.graalvm.version="21.3.0-devd58f689da739" -Dorg.graalvm.config="Mandrel Distribution" --upgrade-module-path ${location}/../../jvmci/graal.jar --add-modules org.graalvm.truffle,org.graalvm.sdk --module-path ${location}/../../truffle/truffle-api.jar:${location}/../../jvmci/graal-sdk.jar "${jvm_args[@]}" ${app_path_arg} "${cp_or_mp}" ${main_class} "${launcher_args[@]}"
DEBUG [build] Build native agents...
DEBUG [OperatingSystem] Execute [/home/karm/tmp/mandrel-java11-21.3-SNAPSHOT/lib/svm/bin/native-image, --macro:native-image-agent-library] in /home/karm/tmp
Error occurred during initialization of boot layer
java.lang.module.FindException: Module jdk.scripting.nashorn not found, required by org.graalvm.nativeimage.builder
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1672)
	at build.buildAgents(build.java:182)
	at build.main(build.java:164)
Caused by: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1657)
	at build.buildAgents(build.java:182)
	at build.main(build.java:164)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:419)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:192)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:132)
Error occurred during initialization of boot layer
```

**Comment by Karm** [comment]
Source: https://github.com/oracle/graal/blob/master/substratevm/mx.substratevm/suite.py#L1096

```
                "requires": [
                    "java.management",
                    "jdk.management",
                    "java.xml.crypto",
                    "java.desktop",
                    "java.security.sasl",
                    "java.smartcardio",
                    "java.net.http",
                    "jdk.sctp",
                    "jdk.scripting.nashorn@11..14",
                ],
```

Does 11..14 mean that it shouldn't be required on my JDK 17?

**Comment by zakkak** [comment]
> Does 11..14 mean that it shouldn't be required on my JDK 17?

Correct! I am not sure why you are getting the above failure :/

**Comment by jerboaa** [comment]
This issue is fixed upstream with:
https://github.com/oracle/graal/pull/3793

Prior https://github.com/graalvm/mandrel-packaging/pull/170 the nashorn dep was pulled unconditionally, thus failing the JDK 17 build because it no longer has nashorn (https://openjdk.java.net/jeps/372, JDK 15). We don't need to do anything after https://github.com/oracle/graal/pull/3793 as it takes care of verifying nashorn is available (on the classpath or module path). If it's not there it'll skip substitutions.

**Comment by jerboaa** [comment]
See also: https://github.com/graalvm/mandrel-packaging/pull/189
