### ISSUE TITLE
Mandrel 21.3 fails to build

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#290]
Mandrel 21.3 fails to build.

[The build](https://github.com/graalvm/mandrel/runs/3665374160?check_suite_focus=true) fails with:
```
Error: Could not find or load main class Distribution
Caused by: java.lang.ClassNotFoundException: Distribution
Error: Image build request failed with exit status 1
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1733)
	at build.buildAgents(build.java:188)
	at build.main(build.java:170)
Caused by: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1718)
	at build.buildAgents(build.java:188)
	at build.main(build.java:170)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:404)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:179)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:119)
```

due to https://github.com/oracle/graal/issues/3769 which is being fixed by @jerboaa and @karm in https://github.com/oracle/graal/pull/3775

**Comment by zakkak** [comment]
I cherry-picked https://github.com/oracle/graal/pull/3775/commits/d11728e723493af8c5c2cf71752f6e3d55d06213 on mandrel/21.3 to get the CI running till it gets merged upstream. 

Note: As I periodically rebase `mandrel/21.3` on oracle/graal's `release/graal-vm/21.3` the cherry-pick will eventually be dropped once the commit makes it in upstream 21.3.

**Comment by zakkak** [comment]
The fix has now been merged upstream https://github.com/oracle/graal/pull/3775 (https://github.com/oracle/graal/commit/9579cc938af8a725c6a5a7a5aed84d67fa90dcd9 for 21.3)
