### ISSUE TITLE
Java 11: Mandrel master Linux build failure: Compiling org.graalvm.libgraal.jni with javac-daemon

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel#311]
```
[wrote /home/tester/jenkins/workspace/mandrel-master-linux-build/mandrel/truffle/mxbuild/jdk11/com.oracle.truffle.api.interop/bin/com/oracle/truffle/api/interop/LegacyMetaObjectWrapperGen$1.class]
[wrote /home/tester/jenkins/workspace/mandrel-master-linux-build/mandrel/truffle/mxbuild/jdk11/com.oracle.truffle.api.interop/bin/com/oracle/truffle/api/interop/LegacyMetaObjectWrapperGen.class]
[total 2929ms]
Result = 0
Finished Java compilation for com.oracle.truffle.api.interop
Finished Compiling com.oracle.truffle.api.interop with javac-daemon(JDK 11)
Compiling org.graalvm.libgraal.jni with javac-daemon(JDK 11) failed
[Stopped javac-daemon on port 41165 for Java 11.0.13 (11) from /usr/java/openjdk-11.0.13_8]
[Stopped javac-daemon on port 46883 for Java 11.0.13 (11) from /usr/java/openjdk-11.0.13_8]
[169032 sending 15 to 169218]
Shutting down
Shutting down
  File "/home/tester/jenkins/workspace/mandrel-master-linux-build/mx/mx.py", line 17807, in <module>
    main()
  File "/home/tester/jenkins/workspace/mandrel-master-linux-build/mx/mx.py", line 17787, in main
    retcode = c(command_args)
  File "/home/tester/jenkins/workspace/mandrel-master-linux-build/mx/mx_commands.py", line 147, in __call__
    return self.command_function(*args, **kwargs)
  File "/home/tester/jenkins/workspace/mandrel-master-linux-build/mx/mx.py", line 14473, in build
    abort('{0} build tasks failed'.format(len(failed)))
  File "/home/tester/jenkins/workspace/mandrel-master-linux-build/mx/mx.py", line 4116, in abort
    traceback.print_stack()
1 build tasks failed
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed, exit code: 1
    at OperatingSystem.exec(build.java:1791)
    at SequentialBuild.lambda$build$0(build.java:539)
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
    at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
    at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
    at Mx.build(build.java:823)
    at SequentialBuild.build(build.java:541)
    at build.main(build.java:70)
Caused by: java.lang.RuntimeException: Failed, exit code: 1
    at OperatingSystem.exec(build.java:1776)
    at SequentialBuild.lambda$build$0(build.java:539)
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
    at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
    at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
    at Mx.build(build.java:823)
    at SequentialBuild.build(build.java:541)
    at build.main(build.java:70)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:404)
    at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:179)
    at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:119)
```

One of these changes seems to be the culprit, unless it's mx' fault:

* [GR-32840] Gate for polybench interpreter...
* [GR-32840] Gate for polybench compiler and warmup...
* [GR-32840] Workaround for hocon issues...
* Remove unnecessary snippet...
* Move base polybench cmd to the snippet with all commands...
* Fixed result_file...
* [GR-34702] Stale JNI reference in the..
* Hide matcher releated Values in the CFG dump..
* Check isInstantiated in lowering instead of snippet..
* register an object replacer for ResourceBundles..

The last pasing build used:

Mandrel Packaging: 940d7d9515ee19994f252da2b98c548eaa613abc
Mandrel: c02f23a262b33aa08a265cb8abff17a7055191a0
MX: e59884413f247bd45338d993effffa135e2c9c2b

FYI @zakkak

**Comment by zakkak** [comment]
The error message is:

```
/home/runner/work/mandrel/mandrel/mandrel/compiler/src/org.graalvm.libgraal.jni/src/org/graalvm/libgraal/jni/LibGraalJNIMethodScope.java:72: error: cannot find symbol
        CLongPointer currentThreadLastJavaPCOffset = (CLongPointer) WordFactory.unsigned(HotSpotJVMCIRuntime.runtime().getCurrentJavaThread()).add(getLastJavaPCOffset());
                                                                                                                      ^
  symbol:   method getCurrentJavaThread()
  location: class HotSpotJVMCIRuntime
/home/runner/work/mandrel/mandrel/mandrel/compiler/src/org.graalvm.libgraal.jni/src/org/graalvm/libgraal/jni/LibGraalJNIMethodScope.java:72: warning: [cast] redundant cast to CLongPointer
        CLongPointer currentThreadLastJavaPCOffset = (CLongPointer) WordFactory.unsigned(HotSpotJVMCIRuntime.runtime().getCurrentJavaThread()).add(getLastJavaPCOffset());
                                                     ^
1 error
```

LibGraalJNIMethodScope.java was added in https://github.com/oracle/graal/commit/deb80d4bc6f7115c756c619c45d48375d8109fdf
