### ISSUE TITLE
Latest graal master seems to fail to build for mandrel

### ISSUE THREAD

**Issue by jerboaa** [graalvm/mandrel#387]
## Description
Mandrel using graal vm master fails to build with:
```
Compiling com.oracle.graal.pointsto with javac-daemon(JDK 11)... [dependency GRAAL_PROCESSOR updated]
/home/runner/work/mandrel/mandrel/mandrel/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/meta/ObjectConstantEquality.java:28: error: package org.graalvm.compiler.truffle.compiler.nodes does not exist
import org.graalvm.compiler.truffle.compiler.nodes.ObjectLocationIdentity;
                                                  ^
1 error
Compiling com.oracle.svm.core with javac-daemon(JDK 11): Failed due to error: 1
Compiling com.oracle.svm.core with javac-daemon(JDK 11) failed
1 build tasks failed
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1662)
	at SequentialBuild.lambda$build$0(build.java:529)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at Mx.build(build.java:869)
	at SequentialBuild.build(build.java:531)
	at build.main(build.java:72)
Caused by: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1647)
	at SequentialBuild.lambda$build$0(build.java:529)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at Mx.build(build.java:869)
	at SequentialBuild.build(build.java:531)
	at build.main(build.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:404)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:179)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:119)
Error: Process completed with exit code 1.
```

See: https://github.com/graalvm/mandrel/actions/runs/2465713805

**Comment by zakkak** [comment]
I am reopenning this as a reminder to revert https://github.com/graalvm/mandrel-packaging/pull/251 once https://github.com/oracle/graal/pull/4633 gets merged (in progress for 22.2).
