### ISSUE TITLE
Graal master (22.3-dev) and 22.2-dev not building (Mandrel distribution) with upstream OpenJDK 11 builds

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#394]
MIrror of upstream issue https://github.com/oracle/graal/issues/4655

**Comment by jerboaa** [comment]
The build failure is:

```
Building com.oracle.svm.native.jvm.posix_amd64 with Ninja... [dependency svm-jvmfuncs-fallback-builder updated]
Fatal error: com.oracle.svm.util.ReflectionUtil$ReflectionUtilError: java.lang.NoSuchMethodException: jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.getReflection()
	at org.graalvm.nativeimage.base/com.oracle.svm.util.ReflectionUtil.lookupMethod(ReflectionUtil.java:82)
	at org.graalvm.nativeimage.base/com.oracle.svm.util.ReflectionUtil.lookupMethod(ReflectionUtil.java:69)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.annotation.SubstrateAnnotationExtracter.<clinit>(SubstrateAnnotationExtracter.java:118)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageClassLoaderSupport.<init>(NativeImageClassLoaderSupport.java:157)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.installNativeImageClassLoader(NativeImageGeneratorRunner.java:180)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:123)
Caused by: java.lang.NoSuchMethodException: jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.getReflection()
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2475)
	at org.graalvm.nativeimage.base/com.oracle.svm.util.ReflectionUtil.lookupMethod(ReflectionUtil.java:74)
	... 5 more
Error: Image build request failed with exit status 1
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1678)
	at build.buildAgents(build.java:227)
	at build.main(build.java:209)
Caused by: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1663)
	at build.buildAgents(build.java:227)
	at build.main(build.java:209)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:404)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:179)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:119)
Error: Process completed with exit code 1.
```

**Comment by Karm** [comment]
Is this still the same thing? It doesn't seem to me, but the title of this GH issue brought me here:

JDK 11: [8242dd1044cc](https://github.com/openjdk/jdk11u-dev/commit/8242dd1044cc)
Mandrel: 22.2 [9504096b811](https://github.com/graalvm/mandrel/commit/9504096b811)

amd64, Linux

```
DEBUG [OperatingSystem] Execute [./mandrel-java11-22.2.0-dev9504096b811/lib/svm/bin/native-image, --macro:native-image-agent-library] in /home/tester/workspace/mandrel-22-2-jdk11-latest-linux-amd64 with environment variables []
Fatal error: com.oracle.svm.util.ReflectionUtil$ReflectionUtilError: java.lang.NoSuchMethodException: jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.getReflection()
    at org.graalvm.nativeimage.base/com.oracle.svm.util.ReflectionUtil.lookupMethod(ReflectionUtil.java:82)
    at org.graalvm.nativeimage.base/com.oracle.svm.util.ReflectionUtil.lookupMethod(ReflectionUtil.java:69)
    at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.annotation.SubstrateAnnotationExtracter.<clinit>(SubstrateAnnotationExtracter.java:118)
    at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageClassLoaderSupport.<init>(NativeImageClassLoaderSupport.java:157)
    at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.installNativeImageClassLoader(NativeImageGeneratorRunner.java:180)
    at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:123)
Caused by: java.lang.NoSuchMethodException: jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.getReflection()
    at java.base/java.lang.Class.getDeclaredMethod(Class.java:2475)
    at org.graalvm.nativeimage.base/com.oracle.svm.util.ReflectionUtil.lookupMethod(ReflectionUtil.java:74)
    ... 5 more
Error: Image build request failed with exit status 1
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed, exit code: 1
    at OperatingSystem.exec(build.java:1678)
    at build.buildAgents(build.java:227)
    at build.main(build.java:209)
Caused by: java.lang.RuntimeException: Failed, exit code: 1
    at OperatingSystem.exec(build.java:1663)
    at build.buildAgents(build.java:227)
    at build.main(build.java:209)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:404)
    at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:179)
    at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:119)
```

**Comment by zakkak** [comment]
Yes it's the same issue. The fix is in https://github.com/oracle/graal/pull/4662 and is in the merge queue (it will also land on 22.2 branch once merged)

**Comment by Karm** [comment]
@zakkak O.K.  Thx. Using [foivos_fix-4655](https://github.com/zakkak/mandrel/tree/fix-4655) made it work for me e.g. with JDK 11 [8242dd1044cc](https://github.com/openjdk/jdk11u-dev/commit/8242dd1044cc).

Build with e.g. jdk-11.0.15+10 doesn't work though. Is it expected that the older (current at the moment) JDK would become incompatible?
Or is it just an mx / Pyhton / packaging fail? I observe it both on CI and locally: 
[JDK11.log.zip](https://github.com/graalvm/mandrel/files/8971925/JDK11.log.zip)
mx: 6.0.1
mandrel-packaging: 22.2
Python: 3.9.1 and 3.9.7
```
Compiling com.oracle.svm.graal with javac-daemon(JDK 11) failed
[Stopped javac-daemon on port 44921 for Java 11.0.15 (11) from /var/X/JDKs/jdk-11.0.15+10]
[Stopped javac-daemon on port 39617 for Java 11.0.15 (11) from /var/X/JDKs/jdk-11.0.15+10]
Shutting down
Shutting down
[428056 sending 15 to 428316]
[428056 sending 9 to 428316]
[428056 sending 15 to 428392]
[428056 sending 9 to 428392]
  File "/home/karm/tmp/mx/mx_enter.py", line 41, in <module>
    mx._main_wrapper()
  File "/home/karm/tmp/mx/mx.py", line 17884, in _main_wrapper
    main()
  File "/home/karm/tmp/mx/mx.py", line 17864, in main
    retcode = c(command_args)
  File "/home/karm/tmp/mx/mx_commands.py", line 144, in __call__
    return self.command_function(*args, **kwargs)
  File "/home/karm/tmp/mx/mx.py", line 14552, in build
    abort('{0} build tasks failed'.format(len(failed)))
  File "/home/karm/tmp/mx/mx.py", line 4106, in abort
    traceback.print_stack()
1 build tasks failed
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1678)
	at SequentialBuild.lambda$build$0(build.java:530)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at Mx.build(build.java:870)
	at SequentialBuild.build(build.java:532)
	at build.main(build.java:73)
Caused by: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1663)
	at SequentialBuild.lambda$build$0(build.java:530)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at Mx.build(build.java:870)
	at SequentialBuild.build(build.java:532)
	at build.main(build.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:404)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:179)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:119)
Cannot find native-image tool. Quitting...

```

**Comment by zakkak** [comment]
> Build with e.g. jdk-11.0.15+10 doesn't work though. Is it expected that the older (current at the moment) JDK would become incompatible?

Yes, that should be due to https://github.com/graalvm/mandrel/issues/373.

**Comment by zakkak** [comment]
https://github.com/oracle/graal/pull/4662 is now merged both on `master` and on `release/graal-vm/22.2` upstream branches.
