### ISSUE TITLE
M 22.2.0.0-Final, JDK: 17.0.4+8, Q 2.10.0.Final: java.lang.IllegalAccessError: class io.quarkus.runner.AutoFeature

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel#412]
I thought this was resolved for Q 2.10.0.Final.
Updated runners to Q 2.11.0.Final and re-running...

```
java.lang.IllegalAccessError: class io.quarkus.runner.AutoFeature (in unnamed module @0x6080558) cannot access class org.graalvm.nativeimage.impl.RuntimeClassInitializationSupport (in module org.graalvm.sdk) because module org.graalvm.sdk does not export org.graalvm.nativeimage.impl to unnamed module @0x6080558
	at io.quarkus.runner.AutoFeature.beforeAnalysis(Unknown Source)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:722)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:78)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:722)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:564)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
```

Full log: https://karms.biz/pastebin/22.2.0-final-Q-2.10-fail.txt

**Comment by Karm** [comment]
2.11.0.Final works fine
