### ISSUE TITLE
M 22.2.0.0 fails with java.lang.IllegalAccessExceptions

### ISSUE THREAD

**Issue by sophokles73** [graalvm/mandrel#416]
## Description
I am trying to create a native executable as part of the Eclipse Hono Maven based build using Quarkus 2.10.2.
Howver, the build fails with multiple java.lang.IllegalAccessExceptions being thrown by the `native-image` compiler.

The build succeeds with Mandrel 22.1.0.0.Final.

## How To Reproduce
1. export GRAALVM_HOME=~/mandrel-java17-22.2.0.0-Final
1. export JAVA_HOME=${GRAALVM_HOME}
1. `git clone https://github.com/eclipse/hono.git`
1. `cd hono`
1. `git checkout build_cli_native_executable`
1. `mvn clean install -DskipTests -Pmetrics-prometheus,build-cli-native-executable`

### Configuration:
 - OS: Ubuntu 22.04
 - Architecture: AMD64
 - Mandrel version: 22.2.0.0.Final
 - JDK version: OpenJDK Runtime Environment Temurin-17.0.4+8 (build 17.0.4+8) (the one that Mandrel includes)

## Expected behavior
I expected the building of the native image using `native-image` to succeed

## Additional context
This is the output of the Quarkus Maven plugin running the `native-image` command:
```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /home/hak8fe/git/hono/cli/target/hono-cli-2.1.0-SNAPSHOT-native-image-source-jar/hono-cli-2.1.0-SNAPSHOT-exec.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on native-image 22.2.0.0-Final Mandrel Distribution (Java Version 17.0.4+8)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] /home/hak8fe/graalvm/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Duser.language=en -J-Duser.country=US -J-Dfile.encoding=UTF-8 -H:-ParseOnce -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED --initialize-at-run-time=io.netty.internal.tcnative.SSL,org.apache.kafka.common.security.authenticator.SaslClientAuthenticator -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -J-Djava.awt.headless=true -H:FallbackThreshold=0 --link-at-build-time -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http -H:NativeLinkerOption=-no-pie -H:-UseServiceLoaderFeature -H:+StackTrace -H:AdditionalSecurityProviders=com.sun.security.sasl.Provider,org.apache.kafka.common.security.oauthbearer.internals.OAuthBearerSaslClientProvider,org.apache.kafka.common.security.scram.internals.ScramSaslClientProvider hono-cli-2.1.0-SNAPSHOT-exec -jar hono-cli-2.1.0-SNAPSHOT-exec.jar
========================================================================================================================
GraalVM Native Image: Generating 'hono-cli-2.1.0-SNAPSHOT-exec' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                    (6.9s @ 0.23GB)
 Version info: 'GraalVM 22.2.0.0-Final Java 17 Mandrel Distribution'
 Java version info: '17.0.4+8'
 C compiler: gcc (linux, x86_64, 11.2.0)
 Garbage collector: Serial GC
 5 user-specific feature(s)
 - io.quarkus.caffeine.runtime.graal.CacheConstructorsAutofeature
 - io.quarkus.runner.AutoFeature
 - io.quarkus.runtime.graal.DisableLoggingAutoFeature
 - io.quarkus.runtime.graal.ResourcesFeature
 - org.graalvm.home.HomeFinderFeature: Finds GraalVM paths and its version number
java.lang.IllegalAccessError: class io.quarkus.runner.AutoFeature (in unnamed module @0xf951f40) cannot access class org.graalvm.nativeimage.impl.RuntimeClassInitializationSupport (in module org.graalvm.sdk) because module org.graalvm.sdk does not export org.graalvm.nativeimage.impl to unnamed module @0xf951f40
	at io.quarkus.runner.AutoFeature.beforeAnalysis(Unknown Source)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:722)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:78)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:722)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:564)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)

Fatal error: java.lang.RuntimeException: Failed to load resource META-INF/services/org.jboss.logmanager.MDCProvider
	at io.quarkus.runtime.ResourceHelper.registerResources(ResourceHelper.java:25)
	at io.quarkus.runtime.graal.ResourcesFeature.beforeAnalysis(ResourcesFeature.java:25)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:722)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:78)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:722)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:564)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
Caused by: java.lang.RuntimeException: Failed to register resource META-INF/services/org.jboss.logmanager.MDCProvider
	at io.quarkus.runtime.ResourceHelper.lambda$registerResources$0(ResourceHelper.java:21)
	at io.quarkus.runtime.util.ClassPathUtils.lambda$consumeStream$1(ClassPathUtils.java:180)
	at io.quarkus.runtime.util.ClassPathUtils.readStream(ClassPathUtils.java:201)
	at io.quarkus.runtime.util.ClassPathUtils.consumeStream(ClassPathUtils.java:179)
	at io.quarkus.runtime.util.ClassPathUtils.consumeAsStreams(ClassPathUtils.java:71)
	at io.quarkus.runtime.ResourceHelper.registerResources(ResourceHelper.java:17)
	... 9 more
Caused by: java.lang.IllegalAccessException: class io.quarkus.runtime.ResourceHelper cannot access class com.oracle.svm.core.jdk.Resources (in module org.graalvm.nativeimage.builder) because module org.graalvm.nativeimage.builder does not export com.oracle.svm.core.jdk to unnamed module @f951f40
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
	at java.base/java.lang.reflect.Method.invoke(Method.java:560)
	at io.quarkus.runtime.ResourceHelper.lambda$registerResources$0(ResourceHelper.java:19)
	... 14 more
------------------------------------------------------------------------------------------------------------------------
                         0.3s (3.9% of total time) in 9 GCs | Peak RSS: 0.77GB | CPU load: 3.78
========================================================================================================================
Failed generating 'hono-cli-2.1.0-SNAPSHOT-exec' after 7.0s.
Error: Image build request failed with exit status 1
```

**Comment by sophokles73** [comment]
I stumbled across the [GraalVM 22.2.0 release notes](https://www.graalvm.org/release-notes/22_2/#native-image) which explain why I get these exceptions.

I have fixed the problem by passing the following arguments to the `native-image` compiler
```
-J--add-opens=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk=ALL-UNNAMED
-J--add-opens=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.localization=ALL-UNNAMED
-J--add-opens=org.graalvm.nativeimage.base/com.oracle.svm.util=ALL-UNNAMED
-J--add-opens=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED
```

with these the build succeeds as expected.
