### ISSUE TITLE
[23.0] Windows build needs to account for new extended socket options in JDK 17.0.10

### ISSUE THREAD

**Issue by jerboaa** [graalvm/mandrel#611]
In CI we see this failure:

```
    Creating library C:\Users\RUNNER~1\AppData\Local\Temp\SVM-18141433008043533303\quarkus-integration-test-resteasy-jackson-999-SNAPSHOT-runner.lib and object C:\Users\RUNNER~1\AppData\Local\Temp\SVM-18141433008043533303\quarkus-integration-test-resteasy-jackson-999-SNAPSHOT-runner.exp
quarkus-integration-test-resteasy-jackson-999-SNAPSHOT-runner.obj : error LNK2001: unresolved external symbol Java_jdk_net_WindowsSocketOptions_getTcpKeepAliveIntvl0
quarkus-integration-test-resteasy-jackson-999-SNAPSHOT-runner.obj : error LNK2001: unresolved external symbol Java_jdk_net_WindowsSocketOptions_getTcpKeepAliveProbes0
quarkus-integration-test-resteasy-jackson-999-SNAPSHOT-runner.obj : error LNK2001: unresolved external symbol Java_jdk_net_WindowsSocketOptions_getTcpKeepAliveTime0
quarkus-integration-test-resteasy-jackson-999-SNAPSHOT-runner.obj : error LNK2001: unresolved external symbol Java_jdk_net_WindowsSocketOptions_setTcpKeepAliveIntvl0
quarkus-integration-test-resteasy-jackson-999-SNAPSHOT-runner.obj : error LNK2001: unresolved external symbol Java_jdk_net_WindowsSocketOptions_setTcpKeepAliveProbes0
quarkus-integration-test-resteasy-jackson-999-SNAPSHOT-runner.obj : error LNK2001: unresolved external symbol Java_jdk_net_WindowsSocketOptions_setTcpKeepAliveTime0
D:\a\mandrel\mandrel\quarkus\integration-tests\resteasy-jackson\target\quarkus-integration-test-resteasy-jackson-999-SNAPSHOT-native-image-source-jar\quarkus-integration-test-resteasy-jackson-999-SNAPSHOT-runner.exe : fatal error LNK1120: 6 unresolved externals
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:204)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.runLinkerCommand(NativeImageViaCC.java:151)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:117)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:724)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:539)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:408)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:612)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:134)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)
```

See: https://github.com/graalvm/mandrel/actions/runs/6810306032/job/18519936281?pr=609#step:13:2725

This is likely due to the new backport in JDK 17.0.10 adding new extended socket options for Windows. JDK bug:
https://bugs.openjdk.org/browse/JDK-8308593

Since the Linux code already had support for this, whatever is done for Linux in GraalVM will now likely also apply to Windows.

**Comment by zakkak** [comment]
Closed via https://github.com/graalvm/mandrel/pull/615
