### ISSUE TITLE
[CI] Mandrel Windows build failing to produce native image agents, doesn't fail the build

### ISSUE THREAD

**Issue by jerboaa** [graalvm/mandrel#636]
## Description
When we build Mandrel for Windows in CI the build doesn't fail if the native image agents fail to build. We need to correct this as it just makes triage more difficult. It starts to run tests - some of which are then bound to fail - while the actual mandrel build was incomplete. Example:

```
[...]
========================================================================================================================
GraalVM Native Image: Generating 'native-image-agent' (shared library)...
========================================================================================================================
For detailed information and explanations on the build output, visit:
https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/BuildOutput.md
------------------------------------------------------------------------------------------------------------------------

[1/8] Initializing...                                                                                    (0.0s @ 0.07GB)
Error: Could not find target method: private native com.oracle.svm.core.hub.Target_java_lang_PublicMethods_MethodList com.oracle.svm.core.hub.DynamicHub.getMethodsRecursive(java.lang.String,java.lang.Class[],boolean,boolean)
------------------------------------------------------------------------------------------------------------------------
                        0.2s (4.9% of total time) in 10 GCs | Peak RSS: 0.30GB | CPU load: 2.72
========================================================================================================================
Finished generating 'native-image-agent' in 3.1s.
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1827)
	at build.buildAgents(build.java:316)
	at build.main(build.java:259)
Caused by: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1816)
	at build.buildAgents(build.java:316)
	at build.main(build.java:259)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:484)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:208)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:135)
native-image 22-beta 2024-03-19
OpenJDK Runtime Environment Mandrel-24.0.0-dev44554595 (build 22-beta+26-ea)
OpenJDK 64-Bit Server VM Mandrel-24.0.0-dev44554595 (build 22-beta+26-ea, mixed mode)
```
https://github.com/graalvm/mandrel/actions/runs/7216793492/job/19663590268#step:8:459

Then results in those strange test reports in Mandrel IT like here:
https://github.com/Karm/mandrel-integration-tests/issues/207#issuecomment-1857192814

## Expected Behaviour
Failing to produce the native image agents should fail the Mandrel build. I.e. Exit with error.

**Comment by zakkak** [comment]
Duplicate of https://github.com/graalvm/mandrel/issues/555?

**Comment by jerboaa** [comment]
yes. Sorry.
