### ISSUE TITLE
Mandrel builds of `graal/master` fail 

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#681]
## Description
$title

```
Failed generating 'native-image-agent' after 9.4s.

The build process encountered an unexpected error:

> com.oracle.svm.core.util.VMError$HostedError: InternalFeature defined by com.oracle.svm.hosted.SecurityServicesFeature unexpectedly failed with a(n) com.oracle.svm.util.ReflectionUtil$ReflectionUtilError

Please inspect the generated error report at:
D:\a\mandrel\mandrelvm\bin\svm_err_b_20240220T012925.583_pid740.md

If you are unable to resolve this problem, please file an issue with the error report at:
https://graalvm.org/support
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1810)
	at build.buildAgents(build.java:290)
	at build.main(build.java:233)
Caused by: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1799)
	at build.buildAgents(build.java:290)
	at build.main(build.java:233)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at jdk.compiler/com.sun.tools.javac.launcher.SourceLauncher.execute(SourceLauncher.java:264)
	at jdk.compiler/com.sun.tools.javac.launcher.SourceLauncher.run(SourceLauncher.java:153)
	at jdk.compiler/com.sun.tools.javac.launcher.SourceLauncher.main(SourceLauncher.java:78)
```

See https://github.com/graalvm/mandrel/actions/runs/7967159240/job/21749520792

## Additional context

We are [currently not storing the generated error reports in CI runs](https://github.com/graalvm/mandrel/issues/682), so we will need to reproduce this locally to get further info.

**Comment by jerboaa** [comment]
Seems fixed in the latest runs.
