### ISSUE TITLE
“Unrecognized option: —enable-sbom" error when passing —enable-sbom as quarkus.native.additional-build-args

### ISSUE THREAD

**Issue by DavidDatagrate** [graalvm/mandrel#703]
## Description
We are creating a native image with quarkus / quarkus maven plugin and would like to have it create an sbom. We pass the --enable-sbom param as quarkus.native.additional-build-args. But when using this option we get the following error: "Error: Unrecognized option: --enable-sbom".

## How To Reproduce
The following command is used 
`/opt/mandrel/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dlogging.initial-configurator.min-level=500 -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Duser.country=US -J-Dfile.encoding=UTF-8 --features=io.quarkus.runner.Feature,io.quarkus.runtime.graal.DisableLoggingFeature -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -J--add-opens=java.base/java.io=ALL-UNNAMED -J--add-opens=java.base/java.lang.invoke=ALL-UNNAMED -J--add-opens=java.base/java.util=ALL-UNNAMED -H:BuildOutputJSONFile=camel-k-integration-2.2.0-runner-build-output-stats.json --enable-sbom -H:+AllowFoldMethods -J-Djava.awt.headless=true --no-fallback --link-at-build-time -H:+ReportExceptionStackTraces -H:-AddAllCharsets --enable-url-protocols=http,https -H:NativeLinkerOption=-no-pie -H:-UseServiceLoaderFeature -H:+StackTrace -J--add-exports=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED --exclude-config io\.netty\.netty-codec /META-INF/native-image/io\.netty/netty-codec/generated/handlers/reflect-config\.json --exclude-config io\.netty\.netty-handler /META-INF/native-image/io\.netty/netty-handler/generated/handlers/reflect-config\.json camel-k-integration-2.2.0-runner -jar camel-k-integration-2.2.0-runner.jar `

### Configuration:
 - OS: Linux 5.15.49
 - Architecture: ARM64
 - Mandrel version: Mandrel-23.0.3.0-Final
 - JDK version: OpenJDK 17.0.10

## Expected behavior
The option —-enable-sbom should be accepted.

## Additional context
The build is triggered by a camel k operator.
```
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /home/quarkus/.m2/wrapper/dists/apache-maven-3.8.6-bin/5f1464e3/apache-maven-3.8.6
Java version: 17.0.10, vendor: Eclipse Adoptium, runtime: /opt/mandrel
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.49-linuxkit-pr", arch: "aarch64", family: "unix"
[INFO] Scanning for projects...
[INFO] 
[INFO] Using the MultiThreadedBuilder implementation with a thread count of 8
[INFO] 
[INFO] ---------< org.apache.camel.k.integration:camel-k-integration >---------
[INFO] Building camel-k-integration 2.2.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ camel-k-integration ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ camel-k-integration ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ camel-k-integration ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /builder/kit-cnuopvj9ujac73ea1410/maven/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ camel-k-integration ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ camel-k-integration ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ camel-k-integration ---
[INFO] 
[INFO] --- quarkus-maven-plugin:3.2.9.Final:build (build-integration) @ camel-k-integration ---
[INFO] HotDeployment files:
[INFO] - routes/Logging.java
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: /builder/kit-cnuopvj9ujac73ea1410/maven/target/camel-k-integration-2.2.0-native-image-source-jar/camel-k-integration-2.2.0-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /builder/kit-cnuopvj9ujac73ea1410/maven/target/camel-k-integration-2.2.0-native-image-source-jar/camel-k-integration-2.2.0-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on native-image 17.0.10 2024-01-16
OpenJDK Runtime Environment Mandrel-23.0.3.0-Final (build 17.0.10+7)
OpenJDK 64-Bit Server VM Mandrel-23.0.3.0-Final (build 17.0.10+7, mixed mode)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] /opt/mandrel/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dlogging.initial-configurator.min-level=500 -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Duser.country=US -J-Dfile.encoding=UTF-8 --features=io.quarkus.runner.Feature,io.quarkus.runtime.graal.DisableLoggingFeature -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -J--add-opens=java.base/java.io=ALL-UNNAMED -J--add-opens=java.base/java.lang.invoke=ALL-UNNAMED -J--add-opens=java.base/java.util=ALL-UNNAMED -H:BuildOutputJSONFile=camel-k-integration-2.2.0-runner-build-output-stats.json --enable-sbom -H:+AllowFoldMethods -J-Djava.awt.headless=true --no-fallback --link-at-build-time -H:+ReportExceptionStackTraces -H:-AddAllCharsets --enable-url-protocols=http,https -H:NativeLinkerOption=-no-pie -H:-UseServiceLoaderFeature -H:+StackTrace -J--add-exports=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED --exclude-config io\.netty\.netty-codec /META-INF/native-image/io\.netty/netty-codec/generated/handlers/reflect-config\.json --exclude-config io\.netty\.netty-handler /META-INF/native-image/io\.netty/netty-handler/generated/handlers/reflect-config\.json camel-k-integration-2.2.0-runner -jar camel-k-integration-2.2.0-runner.jar
Error: Unrecognized option: --enable-sbom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  38.813 s (Wall Clock)
[INFO] Finished at: 2024-03-22T13:54:25Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.2.9.Final:build (build-integration) on project camel-k-integration: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]     [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: io.quarkus.deployment.pkg.steps.NativeImageBuildStep$ImageGenerationFailureException: Image generation failed. Exit code: 20
[ERROR]     at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:457)
[ERROR]     at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:263)
[ERROR]     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]     at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
[ERROR]     at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
[ERROR]     at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]     at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR]     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[ERROR]     at java.base/java.lang.Thread.run(Thread.java:840)
[ERROR]     at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Stream closed EOF for default/camel-k-kit-cnuopvj9ujac73ea1410-builder (quarkus-native)
```

**Comment by jerboaa** [comment]
`--enable-sbom` is an [Oracle GraalVM only feature](https://www.graalvm.org/latest/security-guide/native-image/#software-bill-of-materials), not available in GraalVM for JDK 17 Community, thus, Mandrel 23.0. This is not a bug. Sorry.

**Comment by DavidDatagrate** [comment]
ok got it. Thank you for the quick reply. Is there any plans to support SBOM creation in the future.

**Comment by DavidDatagrate** [comment]
I was referring to https://raw.githubusercontent.com/graalvm/mandrel/mandrel/23.0/docs/reference-manual/native-image/BuildOptions.md and thought since it is listed it would be supported.

**Comment by jerboaa** [comment]
> I was referring to https://raw.githubusercontent.com/graalvm/mandrel/mandrel/23.0/docs/reference-manual/native-image/BuildOptions.md and thought since it is listed it would be supported.

We are a GraalVM downstream distro, which is why we inherit that file. The upstream version is:
https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/BuildOptions.md
