### ISSUE TITLE
JDK 24.latest + GraalVM 24.latest: ReflectionFactory.useOldSerializableConstructor

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel#806]
The latest GraalVM head https://github.com/oracle/graal/commit/6563fe4539d does not build with the latest JDK head https://github.com/openjdk/jdk/commit/4635351b157 resulting in an error at the very end of the build process when a native-image is to be use the first time to compile an agent tool:

```
DEBUG [build] Launcher line AFTER: exec "${location}/../../../bin/java" -XX:MaxHeapSize=214748365 -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -Dorg.graalvm.version="24.2.0-dev33ff332c0b1c" -Dorg.graalvm.vendorversion="Mandrel-24.2.0-dev33ff332c0b1c" -Dorg.graalvm.vendor="Karm, Inc." -Dorg.graalvm.vendorurl="https://karms.biz/bugs?component="foo"&version="1.0.x-ab"" --upgrade-module-path "${location}/../../jvmci/graal.jar" "${jvm_args[@]}" ${app_path_arg} "${cp_or_mp}" ${main_class} "${launcher_args[@]}"
DEBUG [build] Build native agents...
DEBUG [OperatingSystem] Execute [/home/karm/tmp/mandrel-24.2.0-SNAPSHOT/lib/svm/bin/native-image, --macro:native-image-agent-library] in /home/karm/tmp with environment variables []
WARNING: Unknown module: org.graalvm.truffle specified to --enable-native-access
========================================================================================================================
GraalVM Native Image: Generating 'libnative-image-agent' (shared library)...
========================================================================================================================
For detailed information and explanations on the build output, visit:
https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/BuildOutput.md
------------------------------------------------------------------------------------------------------------------------

[1/8] Initializing...                                                                                    (0.0s @ 0.12GB)
Error: Could not find target method: static boolean com.oracle.svm.core.hub.Target_jdk_internal_reflect_ReflectionFactory.useOldSerializableConstructor()
------------------------------------------------------------------------------------------------------------------------
                         0.1s (2.2% of total time) in 3 GCs | Peak RSS: 0.55GB | CPU load: 6.77
========================================================================================================================
Failed generating 'libnative-image-agent' after 2.1s.
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1873)
	at build.buildAgents(build.java:304)
	at build.main(build.java:247)
Caused by: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1862)
	at build.buildAgents(build.java:304)
	at build.main(build.java:247)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:573)
	at jdk.compiler/com.sun.tools.javac.launcher.SourceLauncher.execute(SourceLauncher.java:269)
	at jdk.compiler/com.sun.tools.javac.launcher.SourceLauncher.run(SourceLauncher.java:153)
	at jdk.compiler/com.sun.tools.javac.launcher.SourceLauncher.main(SourceLauncher.java:78)
WARNING: Unknown module: org.graalvm.truffle specified to --enable-native-access
========================================================================================================================
```

Also compiling a plain hello world fails the same way:

```
GraalVM Native Image: Generating 'hello' (executable)...
========================================================================================================================
For detailed information and explanations on the build output, visit:
https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/BuildOutput.md
------------------------------------------------------------------------------------------------------------------------

[1/8] Initializing...                                                                                    (0.0s @ 0.27GB)
Error: Could not find target method: static boolean com.oracle.svm.core.hub.Target_jdk_internal_reflect_ReflectionFactory.useOldSerializableConstructor()
```

FYI @zakkak

**Comment by jerboaa** [comment]
@Karm Please uses the latest tagged JDK 24 EA build (you can check out the tag and do your dev work based on that then rebase to TIP once tested with GraalVM). Latest is likely to break often.

Our latest CI build built fine with: `jdk-24+20`.

**Comment by Karm** [comment]
@jerboaa I can see the +20-ea working just fine too: https://ci.modcluster.io/view/Mandrel/job/mandrel-master-linux-build-matrix/1562/JDK_RELEASE=ea,JDK_VERSION=24,LABEL=el8/  

I filed this issue when it fell apart on my laptop. Are you saying that it's better not to follow up on it as it will gradually get sorted later on the main Graal repo anyway?   I didn't mean to add more entropy...

**Comment by jerboaa** [comment]
> I filed this issue when it fell apart on my laptop. Are you saying that it's better not to follow up on it as it will gradually get sorted later on the main Graal repo anyway?

Yes.

**Comment by jerboaa** [comment]
I'm going to close this as we don't track JDK head and GraalVM build issues in that detailed way.
